/*
 long.js (c) 2013 Daniel Wirtz <dcode@dcode.io>
 Released under the Apache License, Version 2.0
 see: https://github.com/dcodeIO/long.js for details
*/
function g(a,c){this.g=a;this.f=c}function h(a,c,b){this.g=a;this.f=c;this.h=b}function l(a,c,b){this.g=0;this.f=a;this.h=c;this.G=b}function aa(a,c,b,d){this.g=0;this.f=a;this.h=c;this.G=b;this.d=d}function ba(a,c,b,d,e){this.g=0;this.f=a;this.h=c;this.G=b;this.d=d;this.e=e}function ca(a){var c=p,b=p,d=p,e=p;this.g=0;this.f=c;this.h=7;this.G=b;this.d=a;this.e=d;this.l=e}function r(a,c){this.l=a;void 0===c&&(this.x=da)}function t(a){this.l=a}
function u(a,c){this.l=a;this.D=c;this.arity=a.length-c.length}var p=new function(a){this.g=a}(0),ea={},da={},fa={};
function v(a,c){for(;;)if(a=x(a),a instanceof Function){if(c.length===a.length)return a.apply(null,c);if(c.length<a.length)return new u(a,c);var b=a.apply(null,c.slice(0,a.length));c=c.slice(a.length);a=y(b)}else if(a instanceof u){if(c.length===a.arity)return a.l.apply(null,a.D.concat(c));if(c.length<a.arity)return new u(a.l,a.D.concat(c));b=a.l.apply(null,a.D.concat(c.slice(0,a.arity)));c=c.slice(a.arity);a=y(b)}else return a}
function C(a,c){a=x(a);return a instanceof Function?1===a.length?a(c):new u(a,[c]):a instanceof u?1===a.arity?a.l.apply(null,a.D.concat([c])):new u(a.l,a.D.concat([c])):a}
function D(a,c,b){a=x(a);if(a instanceof Function)switch(a.length){case 2:return a(c,b);case 1:return C(y(a(c)),b);default:return new u(a,[c,b])}else if(a instanceof u)switch(a.arity){case 2:return a.l.apply(null,a.D.concat([c,b]));case 1:return C(y(a.l.apply(null,a.D.concat([c]))),b);default:return new u(a.l,a.D.concat([c,b]))}else return a}
function ga(a,c,b,d){a=x(a);if(a instanceof Function)switch(a.length){case 3:return a(c,b,d);case 2:return C(y(a(c,b)),d);case 1:return D(y(a(c)),b,d);default:return new u(a,[c,b,d])}else if(a instanceof u)switch(a.arity){case 3:return a.l.apply(null,a.D.concat([c,b,d]));case 2:return C(y(a.l.apply(null,a.D.concat([c,b]))),d);case 1:return D(y(a.l.apply(null,a.D.concat([c]))),b,d);default:return new u(a.l,a.D.concat([c,b,d]))}else return a}
function x(a){if(a instanceof r){if(a.l!==ea)if(a.x===da){var c=a.l;a.l=ea;a.x=c()}else return a.l();if(a.x===da)throw"Infinite loop!";return a.x}return a}var G=0,ha=[];function y(a){for(ha.push(G);a instanceof t;){var c=a.l;a.l=ea;G=0;a=c()}G=ha.pop();return a}if(!window)var window={};window.Haste={};window.A=v;window.E=x;window.B=y;function ia(a){throw x(a);}function ja(a){ia(H(a))}function J(a){return K(a,p)}
function K(a,c,b){var d=b?b:0;return d>=a.length?x(c):{g:1,f:a.charCodeAt(d),h:new r(function(){return K(a,c,d+1)})}}function L(a){return J(x(a))}function H(a){var c="";for(a=x(a);1==a.g;a=x(a.h))c+=String.fromCharCode(x(a.f));return c}function ka(a,c){a.x=c}var la=Math.trunc?Math.trunc:function(a){return 0>a?Math.ceil(a):Math.floor(a)};if("undefined"==typeof ma)var ma=void 0;var na=new ArrayBuffer(8);new Uint32Array(na);new Float32Array(na);new Float64Array(na);
window.jsGetMouseCoords=function(a){var c=0,b=0;a||(a=window.event);if(a.pageX||a.pageY)c=a.pageX,b=a.pageY;else if(a.clientX||a.clientY)c=a.clientX+document.body.scrollLeft+document.documentElement.scrollLeft,b=a.clientY+document.body.scrollTop+document.documentElement.scrollTop;return[c-(a.currentTarget.offsetLeft||0),b-(a.currentTarget.offsetTop||0)]};function oa(a,c){var b=[];for(a=x(a);a.g;)a=x(a),b.push(x(a.f)),a=x(a.h);return b.join(c)}
function pa(a,c,b){c=new ArrayBuffer(c);(new window[a](c))[0]=b;return c}function qa(a,c,b){var d=new ArrayBuffer(c);(new window[a](d))[0]=b;a=new Uint8Array(d);b=0;for(c=c-1;b<c;++b,--c){var e=a[b];a[b]=a[c];a[c]=e}return d}window.toABle=pa;window.toABbe=qa;var ra=new ArrayBuffer(2);(new DataView(ra)).setInt16(0,256,!0);256!==(new Int16Array(ra))[0]&&(window.toABle=qa,window.toABbe=pa);var M={};
(function(a,c){function b(a,b,c){if(null!==a&&"object"===typeof a&&Array.isArray(a.a))return a;this.c=0;this.a=null;this.length=0;if("le"===b||"be"===b)c=b,b=10;null!==a&&this.ja(a||0,b||10,c||"be")}function d(a,b,c){var d=0;for(c=Math.min(a.length,c);b<c;b++)var e=a.charCodeAt(b)-48,d=d<<4,d=49<=e&&54>=e?d|e-49+10:17<=e&&22>=e?d|e-17+10:d|e&15;return d}function e(a,b,c,d){var e=0;for(c=Math.min(a.length,c);b<c;b++)var f=a.charCodeAt(b)-48,e=e*d,e=49<=f?e+(f-49+10):17<=f?e+(f-17+10):e+f;return e}
"object"===typeof a?a.Ra=b:c.M=b;b.M=b;b.$=26;b.max=function(a,b){return 0<a.N(b)?a:b};b.min=function(a,b){return 0>a.N(b)?a:b};b.prototype.ja=function(a,b,c){if("number"===typeof a)this.ka(a,b,c);else if("object"===typeof a)this.T(a,b,c);else{"hex"===b&&(b=16);a=a.toString().replace(/\s+/g,"");var d=0;"-"===a[0]&&d++;16===b?this.ma(a,d):this.la(a,b,d);"-"===a[0]&&(this.c=1);this.u();"le"===c&&this.T(this.ia(),b,c)}};b.prototype.ka=function(a,b,c){0>a&&(this.c=1,a=-a);67108864>a?(this.a=[a&67108863],
this.length=1):4503599627370496>a?(this.a=[a&67108863,a/67108864&67108863],this.length=2):(this.a=[a&67108863,a/67108864&67108863,1],this.length=3);"le"===c&&this.T(this.ia(),b,c)};b.prototype.T=function(a,b,c){if(0>=a.length)this.a=[0],this.length=1;else{this.length=Math.ceil(a.length/3);this.a=Array(this.length);for(b=0;b<this.length;b++)this.a[b]=0;var d=0;if("be"===c)for(b=a.length-1,c=0;0<=b;b-=3){var e=a[b]|a[b-1]<<8|a[b-2]<<16;this.a[c]|=e<<d&67108863;this.a[c+1]=e>>>26-d&67108863;d+=24;26<=
d&&(d-=26,c++)}else if("le"===c)for(c=b=0;b<a.length;b+=3)e=a[b]|a[b+1]<<8|a[b+2]<<16,this.a[c]|=e<<d&67108863,this.a[c+1]=e>>>26-d&67108863,d+=24,26<=d&&(d-=26,c++);this.u()}};b.prototype.ma=function(a,b){this.length=Math.ceil((a.length-b)/6);this.a=Array(this.length);for(var c=0;c<this.length;c++)this.a[c]=0;for(var e=0,c=a.length-6,f=0;c>=b;c-=6){var w=d(a,c,c+6);this.a[f]|=w<<e&67108863;this.a[f+1]|=w>>>26-e&4194303;e+=24;26<=e&&(e-=26,f++)}c+6!==b&&(w=d(a,b,c+6),this.a[f]|=w<<e&67108863,this.a[f+
1]|=w>>>26-e&4194303);this.u()};b.prototype.la=function(a,b,c){this.a=[0];this.length=1;for(var d=0,f=1;67108863>=f;f*=b)d++;d--;for(var f=f/b|0,w=a.length-c,k=w%d,q=Math.min(w,w-k)+c,w=0;c<q;c+=d)w=e(a,c,c+d,b),this.ca(f),67108864>this.a[0]+w?this.a[0]+=w:this.Y(w);if(0!==k){d=1;w=e(a,c,a.length,b);for(c=0;c<k;c++)d*=b;this.ca(d);67108864>this.a[0]+w?this.a[0]+=w:this.Y(w)}};b.prototype.ra=function(a){a.a=Array(this.length);for(var b=0;b<this.length;b++)a.a[b]=this.a[b];a.length=this.length;a.c=
this.c};b.prototype.clone=function(){var a=new b(null);this.ra(a);return a};b.prototype.u=function(){for(;1<this.length&&0===this.a[this.length-1];)this.length--;return this.J()};b.prototype.J=function(){1===this.length&&0===this.a[0]&&(this.c=0);return this};var f=" 0 00 000 0000 00000 000000 0000000 00000000 000000000 0000000000 00000000000 000000000000 0000000000000 00000000000000 000000000000000 0000000000000000 00000000000000000 000000000000000000 0000000000000000000 00000000000000000000 000000000000000000000 0000000000000000000000 00000000000000000000000 000000000000000000000000 0000000000000000000000000".split(" "),
k=[0,0,25,16,12,11,10,9,8,8,7,7,7,7,6,6,6,6,6,6,6,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5],m=[0,0,33554432,43046721,16777216,48828125,60466176,40353607,16777216,43046721,1E7,19487171,35831808,62748517,7529536,11390625,16777216,24137569,34012224,47045881,64E6,4084101,5153632,6436343,7962624,9765625,11881376,14348907,17210368,20511149,243E5,28629151,33554432,39135393,45435424,52521875,60466176];b.prototype.toString=function(a,b){a=a||10;b=b|0||1;if(16===a||"hex"===a){for(var c="",d=0,e=0,w=0;w<this.length;w++){var z=
this.a[w],q=((z<<d|e)&16777215).toString(16),e=z>>>24-d&16777215,c=0!==e||w!==this.length-1?f[6-q.length]+q+c:q+c,d=d+2;26<=d&&(d-=26,w--)}for(0!==e&&(c=e.toString(16)+c);0!==c.length%b;)c="0"+c;0!==this.c&&(c="-"+c);return c}if(a===(a|0)&&2<=a&&36>=a){d=k[a];e=m[a];c="";w=this.clone();for(w.c=0;0!==w.I();)z=w.W(e).toString(a),w=w.ba(e),c=0!==w.I()?f[d-z.length]+z+c:z+c;for(0===this.I()&&(c="0"+c);0!==c.length%b;)c="0"+c;0!==this.c&&(c="-"+c);return c}throw"Base should be between 2 and 36";};b.prototype.toJSON=
function(){return this.toString(16)};b.prototype.ia=function(){this.u();var a=Array(this.byteLength());a[0]=0;for(var b=this.clone(),c=0;0!==b.I();c++){var d=b.oa();b.fa(8);a[a.length-c-1]=d}return a};b.prototype.X=Math.qa?function(a){return 32-Math.qa(a)}:function(a){var b=0;4096<=a&&(b+=13,a>>>=13);64<=a&&(b+=7,a>>>=7);8<=a&&(b+=4,a>>>=4);2<=a&&(b+=2,a>>>=2);return b+a};b.prototype.pa=function(){var a=0,a=this.X(this.a[this.length-1]);return 26*(this.length-1)+a};b.prototype.byteLength=function(){return Math.ceil(this.pa()/
8)};b.prototype.o=function(){if(0===this.I())return this.clone();var a=this.clone();a.c=this.c^1;return a};b.prototype.ya=function(a){for(;this.length<a.length;)this.a[this.length++]=0;for(var b=0;b<a.length;b++)this.a[b]|=a.a[b];return this.u()};b.prototype.da=function(a){return this.ya(a)};b.prototype.Ca=function(a){return this.length>a.length?this.clone().da(a):a.clone().da(this)};b.prototype.xa=function(a){var b;b=this.length>a.length?a:this;for(var c=0;c<b.length;c++)this.a[c]&=a.a[c];this.length=
b.length;return this.u()};b.prototype.aa=function(a){return this.xa(a)};b.prototype.ua=function(a){return this.length>a.length?this.clone().aa(a):a.clone().aa(this)};b.prototype.za=function(a){var b;this.length>a.length?b=this:(b=a,a=this);for(var c=0;c<a.length;c++)this.a[c]=b.a[c]^a.a[c];if(this!==b)for(;c<b.length;c++)this.a[c]=b.a[c];this.length=b.length;return this.u()};b.prototype.ga=function(a){return this.za(a)};b.prototype.Ga=function(a){return this.length>a.length?this.clone().ga(a):a.clone().ga(this)};
b.prototype.P=function(a){if(0!==this.c&&0===a.c){this.c=0;var b=this.R(a);this.c^=1;return this.J()}if(0===this.c&&0!==a.c)return a.c=0,b=this.R(a),a.c=1,b.J();var c;this.length>a.length?c=this:(c=a,a=this);for(var d=b=0;d<a.length;d++)b=(c.a[d]|0)+(a.a[d]|0)+b,this.a[d]=b&67108863,b>>>=26;for(;0!==b&&d<c.length;d++)b=(c.a[d]|0)+b,this.a[d]=b&67108863,b>>>=26;this.length=c.length;if(0!==b)this.a[this.length]=b,this.length++;else if(c!==this)for(;d<c.length;d++)this.a[d]=c.a[d];return this};b.prototype.add=
function(a){if(0!==a.c&&0===this.c){a.c=0;var b=this.sub(a);a.c^=1;return b}return 0===a.c&&0!==this.c?(this.c=0,b=a.sub(this),this.c=1,b):this.length>a.length?this.clone().P(a):a.clone().P(this)};b.prototype.R=function(a){if(0!==a.c){a.c=0;var b=this.P(a);a.c=1;return b.J()}if(0!==this.c)return this.c=0,this.P(a),this.c=1,this.J();b=this.N(a);if(0===b)return this.c=0,this.length=1,this.a[0]=0,this;var c;0<b?c=this:(c=a,a=this);for(var d=0,e=0;e<a.length;e++)b=(c.a[e]|0)-(a.a[e]|0)+d,d=b>>26,this.a[e]=
b&67108863;for(;0!==d&&e<c.length;e++)b=(c.a[e]|0)+d,d=b>>26,this.a[e]=b&67108863;if(0===d&&e<c.length&&c!==this)for(;e<c.length;e++)this.a[e]=c.a[e];this.length=Math.max(this.length,e);c!==this&&(this.c=1);return this.u()};b.prototype.sub=function(a){return this.clone().R(a)};b.prototype.Da=function(a,b){if(63>this.length+a.length){b.c=a.c^this.c;var c=this.length+a.length|0;b.length=c;var c=c-1|0,d=this.a[0]|0,e=a.a[0]|0,d=d*e,f=d/67108864|0;b.a[0]=d&67108863;for(var k=1;k<c;k++){for(var q=f>>>
26,f=f&67108863,m=Math.min(k,a.length-1),T=Math.max(0,k-this.length+1);T<=m;T++)d=this.a[k-T|0]|0,e=a.a[T]|0,d*=e,e=d&67108863,q=q+(d/67108864|0)|0,e=e+f|0,f=e&67108863,q=q+(e>>>26)|0;b.a[k]=f|0;f=q|0}0!==f?b.a[k]=f|0:b.length--}else{b.c=a.c^this.c;b.length=this.length+a.length;for(k=c=f=0;k<b.length-1;k++){q=c;c=0;f&=67108863;m=Math.min(k,a.length-1);for(T=Math.max(0,k-this.length+1);T<=m;T++)d=(this.a[k-T]|0)*(a.a[T]|0),e=d&67108863,q=q+(d/67108864|0)|0,e=e+f|0,f=e&67108863,q=q+(e>>>26)|0,c+=q>>>
26,q&=67108863;b.a[k]=f;f=q}0!==f?b.a[k]=f:b.length--}return b.u()};b.prototype.H=function(a){var c=new b(null);c.a=Array(this.length+a.length);return this.Da(a,c)};b.prototype.ca=function(a){for(var b=0,c=0;c<this.length;c++){var d=(this.a[c]|0)*a,e=(d&67108863)+(b&67108863),b=b>>26,b=b+(d/67108864|0),b=b+(e>>>26);this.a[c]=e&67108863}0!==b&&(this.a[c]=b,this.length++)};b.prototype.ea=function(a){var b=a%26;a=(a-b)/26;var c=67108863>>>26-b<<26-b;if(0!==b){for(var d=0,e=0;e<this.length;e++){var f=
this.a[e]&c;this.a[e]=(this.a[e]|0)-f<<b|d;d=f>>>26-b}d&&(this.a[e]=d,this.length++)}if(0!==a){for(e=this.length-1;0<=e;e--)this.a[e+a]=this.a[e];for(e=0;e<a;e++)this.a[e]=0;this.length+=a}return this.u()};b.prototype.fa=function(a){var b;b=0;var c=a%26,d=Math.min((a-c)/26,this.length),e=67108863^67108863>>>c<<c;b=Math.max(0,b-d);if(0!==d)if(this.length>d)for(this.length-=d,a=0;a<this.length;a++)this.a[a]=this.a[a+d];else this.a[0]=0,this.length=1;d=0;for(a=this.length-1;0<=a&&(0!==d||a>=b);a--){var f=
this.a[a]|0;this.a[a]=d<<26-c|f>>>c;d=f&e}0===this.length&&(this.a[0]=0,this.length=1);this.u()};b.prototype.Ka=function(a){return this.clone().ea(a)};b.prototype.Y=function(a){this.a[0]+=a;for(a=0;a<this.length&&67108864<=this.a[a];a++)this.a[a]-=67108864,a===this.length-1?this.a[a+1]=1:this.a[a+1]++;this.length=Math.max(this.length,a+1)};b.prototype.wa=function(){this.c=0;return this};b.prototype.abs=function(){return this.clone().wa()};b.prototype.U=function(a,b,c){var d=a.length+c,e;if(this.a.length<
d){var f=Array(d);for(e=0;e<this.length;e++)f[e]=this.a[e];this.a=f}else e=this.length;for(this.length=Math.max(this.length,d);e<this.length;e++)this.a[e]=0;for(e=f=0;e<a.length;e++)d=(this.a[e+c]|0)+f,f=(a.a[e]|0)*b,d-=f&67108863,f=(d>>26)-(f/67108864|0),this.a[e+c]=d&67108863;for(;e<this.length-c;e++)d=(this.a[e+c]|0)+f,f=d>>26,this.a[e+c]=d&67108863;if(0===f)return this.u();for(e=f=0;e<this.length;e++)d=-(this.a[e]|0)+f,f=d>>26,this.a[e]=d&67108863;this.c=1;return this.u()};b.prototype.na=function(a,
c){var d=this.length-a.length,e=this.clone(),f=a,k=f.a[f.length-1]|0,d=26-this.X(k);0!==d&&(f=f.Ka(d),e.ea(d),k=f.a[f.length-1]|0);var z=e.length-f.length,q;if("mod"!==c){q=new b(null);q.length=z+1;q.a=Array(q.length);for(var m=0;m<q.length;m++)q.a[m]=0}m=e.clone().U(f,1,z);0===m.c&&(e=m,q&&(q.a[z]=1));for(--z;0<=z;z--){m=67108864*(e.a[f.length+z]|0)+(e.a[f.length+z-1]|0);m=Math.min(m/k|0,67108863);for(e.U(f,m,z);0!==e.c;)m--,e.c=0,e.U(f,1,z),0!==e.I()&&(e.c^=1);q&&(q.a[z]=m)}q&&q.u();e.u();"div"!==
c&&0!==d&&e.fa(d);return{s:q?q:null,C:e}};b.prototype.K=function(a,c,d){if(0!==this.c&&0===a.c){var e=this.o().K(a,c),f,k;"mod"!==c&&(f=e.s.o());"div"!==c&&(k=e.C.o(),d&&k.o&&(k=k.add(a)));return{s:f,C:k}}return 0===this.c&&0!==a.c?(e=this.K(a.o(),c),"mod"!==c&&(f=e.s.o()),{s:f,C:e.C}):0!==(this.c&a.c)?(e=this.o().K(a.o(),c),"div"!==c&&(k=e.C.o(),d&&k.o&&(k=k.R(a))),{s:e.s,C:k}):a.length>this.length||0>this.N(a)?{s:new b(0),C:this}:1===a.length?"div"===c?{s:this.Z(a.a[0]),C:null}:"mod"===c?{s:null,
C:new b(this.W(a.a[0]))}:{s:this.Z(a.a[0]),C:new b(this.W(a.a[0]))}:this.na(a,c)};b.prototype.s=function(a){return this.K(a,"div",!1).s};b.prototype.C=function(a){return this.K(a,"mod",!1).C};b.prototype.W=function(a){for(var b=67108864%a,c=0,d=this.length-1;0<=d;d--)c=(b*c+(this.a[d]|0))%a;return c};b.prototype.ba=function(a){for(var b=0,c=this.length-1;0<=c;c--)b=(this.a[c]|0)+67108864*b,this.a[c]=b/a|0,b%=a;return this.u()};b.prototype.Z=function(a){return this.clone().ba(a)};b.prototype.V=function(){return 1===
(this.a[0]&1)};b.prototype.oa=function(){return this.a[0]&255};b.prototype.I=function(){var a=0,b=0>a;b&&(a=-a);if(0!==this.c&&!b)return-1;if(0===this.c&&b)return 1;a&=67108863;this.u();1<this.length?a=1:(b=this.a[0]|0,a=b===a?0:b<a?-1:1);0!==this.c&&(a=-a);return a};b.prototype.N=function(a){if(0!==this.c&&0===a.c)return-1;if(0===this.c&&0!==a.c)return 1;a=this.Ja(a);return 0!==this.c?-a:a};b.prototype.Ja=function(a){if(this.length>a.length)return 1;if(this.length<a.length)return-1;for(var b=0,c=
this.length-1;0<=c;c--){var d=this.a[c]|0,e=a.a[c]|0;if(d!==e){d<e?b=-1:d>e&&(b=1);break}}return b}})(void 0,M);M.Qa=new M.M(0);M.ONE=new M.M(1);M.Pa=new M.M(4294967296);function N(a,c,b){this.j=a|0;this.i=c|0;this.m=!!b}var sa={},ta={};function ua(a,c){return c?0<=(a>>>=0)&&256>a:-128<=(a|=0)&&128>a}function va(a,c){var b,d;if(c){if(d=ua(a>>>=0,!0))if(b=ta[a])return b;b=new N(a,0>(a|0)?-1:0,!0);d&&(ta[a]=b)}else{if(d=ua(a|=0,!1))if(b=sa[a])return b;b=new N(a,0>a?-1:0,!1);d&&(sa[a]=b)}return b}
function wa(a,c){if(isNaN(a)||!isFinite(a))return c?xa:O;if(c){if(0>a)return xa;if(a>=ya)return za}else{if(a<=-Ba)return P;if(a+1>=Ba)return Ca}return 0>a?wa(-a,c).o():new N(a%Da|0,a/Da|0,c)}var Ea=Math.pow,Da=4294967296,ya=Da*Da,Ba=ya/2,Fa=va(16777216),O=va(0),xa=va(0,!0),Ga=va(1);va(1,!0);var Ha=va(-1),Ca=new N(-1,2147483647,!1),za=new N(-1,-1,!0),P=new N(0,-2147483648,!1),Q=N.prototype;Q.Ma=function(){return this.m?this.j>>>0:this.j};
Q.S=function(){return this.m?(this.i>>>0)*Da+(this.j>>>0):this.i*Da+(this.j>>>0)};Q.L=function(){return 0===this.i&&0===this.j};Q.F=function(){return!this.m&&0>this.i};Q.V=function(){return 1===(this.j&1)};Q.w=function(a){return this.m!==a.m&&1===this.i>>>31&&1===a.i>>>31?!1:this.i===a.i&&this.j===a.j};Q.Ta=function(a){return!this.w(a)};Q.ha=function(){return 0>this.O(Fa)};Q.Sa=function(a){return 0>=this.O(a)};Q.sa=function(a){return 0<this.O(a)};Q.ta=function(a){return 0<=this.O(a)};
Q.$=function(a){if(this.w(a))return 0;var c=this.F(),b=a.F();return c&&!b?-1:!c&&b?1:this.m?a.i>>>0>this.i>>>0||a.i===this.i&&a.j>>>0>this.j>>>0?-1:1:this.sub(a).F()?-1:1};Q.O=Q.$;Q.Ba=function(){return!this.m&&this.w(P)?P:this.Ea().add(Ga)};Q.o=Q.Ba;
Q.add=function(a){var c=this.i>>>16,b=this.i&65535,d=this.j>>>16,e=a.i>>>16,f=a.i&65535,k=a.j>>>16,m;m=0+((this.j&65535)+(a.j&65535));a=0+(m>>>16);a+=d+k;d=0+(a>>>16);d+=b+f;b=0+(d>>>16);b=b+(c+e)&65535;return new N((a&65535)<<16|m&65535,b<<16|d&65535,this.m)};Q.Fa=function(a){return this.add(a.o())};Q.sub=Q.Fa;
Q.multiply=function(a){if(this.L()||a.L())return O;if(this.w(P))return a.V()?P:O;if(a.w(P))return this.V()?P:O;if(this.F())return a.F()?this.o().H(a.o()):this.o().H(a).o();if(a.F())return this.H(a.o()).o();if(this.ha()&&a.ha())return wa(this.S()*a.S(),this.m);var c=this.i>>>16,b=this.i&65535,d=this.j>>>16,e=this.j&65535,f=a.i>>>16,k=a.i&65535,m=a.j>>>16;a=a.j&65535;var n,F,I,R;R=0+e*a;I=0+(R>>>16);I+=d*a;F=0+(I>>>16);I=(I&65535)+e*m;F+=I>>>16;I&=65535;F+=b*a;n=0+(F>>>16);F=(F&65535)+d*m;n+=F>>>16;
F&=65535;F+=e*k;n+=F>>>16;F&=65535;n=n+(c*a+b*m+d*k+e*f)&65535;return new N(I<<16|R&65535,n<<16|F,this.m)};Q.H=Q.multiply;
Q.va=function(a){if(a.L())throw Error("division by zero");if(this.L())return this.m?xa:O;var c,b,d;if(this.w(P)){if(a.w(Ga)||a.w(Ha))return P;if(a.w(P))return Ga;c=this.Ia().s(a).Ha();if(c.w(O))return a.F()?Ga:Ha;b=this.sub(a.H(c));return d=c.add(b.s(a))}if(a.w(P))return this.m?xa:O;if(this.F())return a.F()?this.o().s(a.o()):this.o().s(a).o();if(a.F())return this.s(a.o()).o();d=O;for(b=this;b.ta(a);){c=Math.max(1,Math.floor(b.S()/a.S()));for(var e=Math.ceil(Math.log(c)/Math.LN2),e=48>=e?1:Ea(2,e-
48),f=wa(c),k=f.H(a);k.F()||k.sa(b);)c-=e,f=wa(c,this.m),k=f.H(a);f.L()&&(f=Ga);d=d.add(f);b=b.sub(k)}return d};Q.s=Q.va;Q.Aa=function(a){return this.sub(this.s(a).H(a))};Q.C=Q.Aa;Q.Ea=function(){return new N(~this.j,~this.i,this.m)};Q.ua=function(a){return new N(this.j&a.j,this.i&a.i,this.m)};Q.Ca=function(a){return new N(this.j|a.j,this.i|a.i,this.m)};Q.Ga=function(a){return new N(this.j^a.j,this.i^a.i,this.m)};
Q.Ha=function(){var a=1;return 0===(a&=63)?this:32>a?new N(this.j<<a,this.i<<a|this.j>>>32-a,this.m):new N(0,this.j<<a-32,this.m)};Q.Ia=function(){var a=1;return 0===(a&=63)?this:32>a?new N(this.j>>>a|this.i<<32-a,this.i>>a,this.m):new N(this.i>>a-32,0<=this.i?0:-1,this.m)};Q.La=function(a){a&=63;if(0===a)return this;var c=this.i;return 32>a?new N(this.j>>>a|c<<32-a,c>>>a,this.m):32===a?new N(c,0,this.m):new N(c>>>a-32,0,this.m)};Q.Na=function(){return this.m?new N(this.j,this.i,!1):this};
Q.Oa=function(){return this.m?this:new N(this.j,this.i,!0)};
function Ia(a,c){var b=a[0],d=a[1],e=a[2],f=a[3],b=S(b,d,e,f,c[0],7,-680876936),f=S(f,b,d,e,c[1],12,-389564586),e=S(e,f,b,d,c[2],17,606105819),d=S(d,e,f,b,c[3],22,-1044525330),b=S(b,d,e,f,c[4],7,-176418897),f=S(f,b,d,e,c[5],12,1200080426),e=S(e,f,b,d,c[6],17,-1473231341),d=S(d,e,f,b,c[7],22,-45705983),b=S(b,d,e,f,c[8],7,1770035416),f=S(f,b,d,e,c[9],12,-1958414417),e=S(e,f,b,d,c[10],17,-42063),d=S(d,e,f,b,c[11],22,-1990404162),b=S(b,d,e,f,c[12],7,1804603682),f=S(f,b,d,e,c[13],12,-40341101),e=S(e,f,
b,d,c[14],17,-1502002290),d=S(d,e,f,b,c[15],22,1236535329),b=U(b,d,e,f,c[1],5,-165796510),f=U(f,b,d,e,c[6],9,-1069501632),e=U(e,f,b,d,c[11],14,643717713),d=U(d,e,f,b,c[0],20,-373897302),b=U(b,d,e,f,c[5],5,-701558691),f=U(f,b,d,e,c[10],9,38016083),e=U(e,f,b,d,c[15],14,-660478335),d=U(d,e,f,b,c[4],20,-405537848),b=U(b,d,e,f,c[9],5,568446438),f=U(f,b,d,e,c[14],9,-1019803690),e=U(e,f,b,d,c[3],14,-187363961),d=U(d,e,f,b,c[8],20,1163531501),b=U(b,d,e,f,c[13],5,-1444681467),f=U(f,b,d,e,c[2],9,-51403784),
e=U(e,f,b,d,c[7],14,1735328473),d=U(d,e,f,b,c[12],20,-1926607734),b=V(d^e^f,b,d,c[5],4,-378558),f=V(b^d^e,f,b,c[8],11,-2022574463),e=V(f^b^d,e,f,c[11],16,1839030562),d=V(e^f^b,d,e,c[14],23,-35309556),b=V(d^e^f,b,d,c[1],4,-1530992060),f=V(b^d^e,f,b,c[4],11,1272893353),e=V(f^b^d,e,f,c[7],16,-155497632),d=V(e^f^b,d,e,c[10],23,-1094730640),b=V(d^e^f,b,d,c[13],4,681279174),f=V(b^d^e,f,b,c[0],11,-358537222),e=V(f^b^d,e,f,c[3],16,-722521979),d=V(e^f^b,d,e,c[6],23,76029189),b=V(d^e^f,b,d,c[9],4,-640364487),
f=V(b^d^e,f,b,c[12],11,-421815835),e=V(f^b^d,e,f,c[15],16,530742520),d=V(e^f^b,d,e,c[2],23,-995338651),b=W(b,d,e,f,c[0],6,-198630844),f=W(f,b,d,e,c[7],10,1126891415),e=W(e,f,b,d,c[14],15,-1416354905),d=W(d,e,f,b,c[5],21,-57434055),b=W(b,d,e,f,c[12],6,1700485571),f=W(f,b,d,e,c[3],10,-1894986606),e=W(e,f,b,d,c[10],15,-1051523),d=W(d,e,f,b,c[1],21,-2054922799),b=W(b,d,e,f,c[8],6,1873313359),f=W(f,b,d,e,c[15],10,-30611744),e=W(e,f,b,d,c[6],15,-1560198380),d=W(d,e,f,b,c[13],21,1309151649),b=W(b,d,e,f,
c[4],6,-145523070),f=W(f,b,d,e,c[11],10,-1120210379),e=W(e,f,b,d,c[2],15,718787259),d=W(d,e,f,b,c[9],21,-343485551);a[0]=b+a[0]&4294967295;a[1]=d+a[1]&4294967295;a[2]=e+a[2]&4294967295;a[3]=f+a[3]&4294967295}function V(a,c,b,d,e,f){c=(c+a&4294967295)+(d+f&4294967295)&4294967295;return(c<<e|c>>>32-e)+b&4294967295}function S(a,c,b,d,e,f,k){return V(c&b|~c&d,a,c,e,f,k)}function U(a,c,b,d,e,f,k){return V(c&d|b&~d,a,c,e,f,k)}function W(a,c,b,d,e,f,k){return V(b^(c|~d),a,c,e,f,k)}
function Ja(a,c){var b=a.v.w8,d=c,e=[1732584193,-271733879,-1732584194,271733878],f;for(f=64;f<=c;f+=64){for(var k=b.subarray(f-64,f),m=[],n=void 0,n=0;64>n;n+=4)m[n>>2]=k[n]+(k[n+1]<<8)+(k[n+2]<<16)+(k[n+3]<<24);Ia(e,m)}b=b.subarray(f-64);c=c<f-64?0:c-(f-64);k=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];for(f=0;f<c;f++)k[f>>2]|=b[f]<<(f%4<<3);k[f>>2]|=128<<(f%4<<3);if(55<f)for(Ia(e,k),f=0;16>f;f++)k[f]=0;k[14]=8*d;Ia(e,k);return e}window.md51=Ja;var Ka="0123456789abcdef".split("");
window.md5=function(a,c){for(var b=Ja(a,c),d=0;d<b.length;d++){for(var e=b[d],f="",k=0;4>k;k++)f+=Ka[e>>8*k+4&15]+Ka[e>>8*k&15];b[d]=f}return b.join("")};window.newByteArr=function(a){var c=8-a%8;8>c&&(a+=c);c={};a=new ArrayBuffer(a);var b={};b.i8=new Int8Array(a);b.i16=new Int16Array(a);b.i32=new Int32Array(a);b.w8=new Uint8Array(a);b.w16=new Uint16Array(a);b.w32=new Uint32Array(a);b.f32=new Float32Array(a);b.f64=new Float64Array(a);c.b=a;c.v=b;c.off=0;return c};
function La(a){var c=x(Ma);return a===c}function Na(a){return a instanceof Function&&2===a.length?function(){var c=a.apply(null,arguments);if(c instanceof r){if(c.l!==ea){var b=c.l;c.l=ea;return c.x=b()}return c.x}for(;c instanceof t;)c=c.l();return x(c)}:function(){var c=Array.prototype.slice.call(arguments);c.push(0);return x(y(v(a,c)))}}function Oa(a,c){return a>=c.length?p:{g:1,f:c[a],h:new r(function(){return Oa(a+1,c)})}}
function X(a,c){var b=x(a);return 0==b.g?x(c):new h(1,b.f,new r(function(){return X(b.h,c)}))}var Pa=new r(function(){return K(") is outside of enumeration's range (0,",new r(function(){var a=new h(1,41,p);return X(L((2).toString()),a)}))});function Qa(a){return ja(K("toEnum{MouseButton}: tag (",new r(function(){return X(L(a.toString()),Pa)})))}function Ra(a,c){return new r(function(){var b=Number(x(a)),b=la(b);return 0>b?Qa(b):2<b?Qa(b):b})}var Sa=new l(0,0,0),Ta=new r(function(){return jsGetMouseCoords});
function Ua(a,c){var b=x(a);if(b.g){var d=Ua(b.h,c);return new h(1,new r(function(){var a=Number(x(b.f));return la(a)}),d)}return p}var Va=new h(0,function(a,c){return new r(function(){var b=Number(x(a));return la(b)})},function(a,c){var b=x(a);return Ua(Oa(0,b),c)});function Wa(a,c){var b=x(a);if(b.g){var d=Wa(b.h,c);return new h(1,b.f,d)}return p}var Xa=new r(function(){return J("base")}),Ya=new r(function(){return J("GHC.IO.Exception")}),Za=new r(function(){return J("IOException")});
function $a(a){return x(new aa(new N(4053623282,1685460941,!0),new N(3693590983,2507416641,!0),new ba(new N(4053623282,1685460941,!0),new N(3693590983,2507416641,!0),Xa,Ya,Za),p))}function ab(a,c,b){a=y(C(a,ma));c=y(C(c,ma));return x(a.f.w(c.f))?0==x(a.h.w(c.h))?p:new g(1,b):p}
var bb=new r(function(){return J(": ")}),cb=new r(function(){return J(" (")}),db=new r(function(){return J("already exists")}),eb=new r(function(){return J("does not exist")}),fb=new r(function(){return J("protocol error")}),gb=new r(function(){return J("failed")}),hb=new r(function(){return J("invalid argument")}),ib=new r(function(){return J("inappropriate type")}),jb=new r(function(){return J("hardware fault")}),kb=new r(function(){return J("unsupported operation")}),lb=new r(function(){return J("timeout")}),
mb=new r(function(){return J("resource vanished")}),nb=new r(function(){return J("interrupted")}),ob=new r(function(){return J("resource busy")}),pb=new r(function(){return J("resource exhausted")}),qb=new r(function(){return J("end of file")}),rb=new r(function(){return J("illegal operation")}),sb=new r(function(){return J("permission denied")}),tb=new r(function(){return J("user error")}),ub=new r(function(){return J("unsatisified constraints")}),vb=new r(function(){return J("system error")});
function wb(a,c){switch(x(a)){case 0:return X(db,c);case 1:return X(eb,c);case 2:return X(ob,c);case 3:return X(pb,c);case 4:return X(qb,c);case 5:return X(rb,c);case 6:return X(sb,c);case 7:return X(tb,c);case 8:return X(ub,c);case 9:return X(vb,c);case 10:return X(fb,c);case 11:return X(gb,c);case 12:return X(hb,c);case 13:return X(ib,c);case 14:return X(jb,c);case 15:return X(kb,c);case 16:return X(lb,c);case 17:return X(mb,c);default:return X(nb,c)}}var xb=new r(function(){return J("{handle: ")});
function yb(a,c,b,d,e,f){var k=new r(function(){var a=new r(function(){return wb(c,new r(function(){var a=x(d);return a.g?X(cb,new r(function(){return X(a,new h(1,41,f))},1)):x(f)},1))},1),e=x(b);return e.g?X(e,new r(function(){return X(bb,a)},1)):x(a)},1);e=x(e);if(e.g)return X(e.f,new r(function(){return X(bb,k)},1));a=x(a);if(a.g){var m=x(a.f);return X(xb,new r(function(){return X(m.f,new h(1,125,new r(function(){return X(bb,k)})))},1))}return x(k)}
function zb(a,c){var b=x(a);return yb(b.f,b.h,b.G,b.d,b.l,c)}function Ab(a,c,b){var d=x(c);return d.g?new h(1,91,new r(function(){return y(D(a,d.f,new r(function(){function c(d){var k=x(d);return k.g?new h(1,44,new r(function(){return y(D(a,k.f,new r(function(){return c(k.h)})))})):x(new h(1,93,b))}return c(d.h)})))})):K("[]",b)}
var Cb=new r(function(){return new aa($a,new l(function(a,c,b){a=x(c);return yb(a.f,a.h,a.G,a.d,a.l,b)},function(a){a=x(a);return yb(a.f,a.h,a.G,a.d,a.l,p)},function(a,c){return Ab(zb,a,c)}),Bb,function(a){a=x(a);return ab(x(x(a.f).f),$a,a.h)})});function Bb(a){return new h(0,Cb,a)}function Db(a,c){return ia(new r(function(){return Bb(new r(function(){return new ca(a)}))}))}var Eb=new r(function(){return J("Pattern match failure in do expression at src/Haste/Prim/Any.hs:272:5-9")});
function Fb(a){return x(x(a).f)}function Gb(a,c){var b=Wa(Oa(0,a),c),d=x(b);if(d.g&&(b=x(d.h),b.g)){if(x(b.h).g)return 19<G?new t(function(){return Db(Eb,c)}):(++G,Db(Eb,c));d=y(ga(Fb,Va,d.f,c));b=y(ga(Fb,Va,b.f,c));return new h(0,d,b)}return 19<G?new t(function(){return Db(Eb,c)}):(++G,Db(Eb,c))}function Hb(a){a=y(C(a,ma));return x(a)}var Ma=new r(function(){return Hb(function(a){return null})});
function Ib(a,c,b){if(7==x(a)){a=x(Ta)(c);var d=y(Gb(a,b)),e=c.deltaX,f=c.deltaY,k=c.deltaZ;return new r(function(){return new l(x(d),x(p),x(new l(e,f,k)))})}a=x(Ta)(c);var m=y(Gb(a,b));c=c.button;if(x(La(c)))return new r(function(){return new l(x(m),x(p),x(Sa))});var n=Ra(c,b);return new r(function(){return new l(x(m),x(new g(1,n)),x(Sa))})}function Jb(a,c,b){return Ib(a,x(c),b)}
function Kb(a){switch(x(a)){case 0:return"click";case 1:return"dblclick";case 2:return"mousedown";case 3:return"mouseup";case 4:return"mousemove";case 5:return"mouseover";case 6:return"mouseout";default:return"wheel"}}function Y(a){return x(a)}var Lb=new h(0,Y,function(a,c){return new g(1,a)}),Mb=new h(0,function(a){return"()"},function(a){a=x(a);return 0==x("()"==a)?p:x(new g(1,0))});function Nb(a){return H(x(a))}var Ob=new h(0,Nb,function(a){return new g(1,new r(function(){return L(x(a))}))});
function Pb(a,c){return a}var Qb=new aa(function(a,c,b){var d=y(C(a,b));return 19<G?new t(function(){return D(c,d,b)}):(++G,D(c,d,b))},function(a,c,b){y(C(a,b));return 19<G?new t(function(){return C(c,b)}):(++G,C(c,b))},Pb,function(a,c){return 19<G?new t(function(){return Db(a,c)}):(++G,Db(a,c))}),Rb=new r(function(){return H(new h(1,38,p))}),Sb=new r(function(){return H(new h(1,61,p))});
function Tb(a,c){var b=x(c);return 0==b.g?p:new h(1,new r(function(){return y(C(a,b.f))}),new r(function(){return Tb(a,b.h)}))}function Ub(a){return x(x(a).f)}function Vb(a,c,b){b=oa(Tb(function(b){var e=x(b);return oa(new h(1,new r(function(){return y(D(Ub,a,e.f))}),new h(1,new r(function(){return y(D(Ub,c,e.h))}),p)),x(Sb))},b),x(Rb));return x(b)}
function Wb(a,c,b,d){var e=new XMLHttpRequest;e.open(a,c,!0);"POST"==a&&e.setRequestHeader("Content-type","application/x-www-form-urlencoded");e.onreadystatechange=function(){4==e.readyState&&d(200==e.status?e.responseText:null)};e.send(b)}var Xb=new r(function(){return H(new h(1,63,p))}),Yb=new r(function(){return H(p)});
function Zb(a,c,b,d,e,f,k,m){function n(a){function n(a){function z(f){function q(b){var c=new r(function(){return x(x(d).h)});Wb(a,f,b,Na(function(a,b){y(D(m,new r(function(){var b=x(a);return x(La(b))?p:y(C(c,new r(function(){return String(b)})))}),b));return Ma}));return 0}if(x(e)){var n=x(k);return n.g?q(Vb(c,b,n)):q(x(Yb))}return q(x(Yb))}if(x(e))return z(H(x(f)));if(x(k).g){var q=oa(new h(1,I,new h(1,F,p)),x(Xb));return z(q)}return z(H(x(f)))}return x(e)?n("POST"):n("GET")}var F=new r(function(){return Vb(c,
b,k)}),I=new r(function(){return Nb(f)});return 19<G?new t(function(){return C(a,n)}):(++G,C(a,n))}function $b(a){return x(x(a).f)}function ac(a){return x(x(a).f)}var bc=new r(function(){return Hb(function(a){return{x:p}})});
function cc(a,c,b,d,e,f,k,m){function n(a){var b=new r(function(){return y(C(c,new r(function(){var b=Na(function(b,c){y(D(x(a),b,c));return Ma});return function(a){a=x(Aa);var c=x(w);a.addEventListener(c,b,!1);return[b]}})))});return 19<G?new t(function(){return D(R,b,F)}):(++G,D(R,b,F))}function F(a){return 19<G?new t(function(){return C(I.G,new l(w,Aa,a))}):(++G,C(I.G,new l(w,Aa,a)))}var I=x(a),R=I.f,Aa=new r(function(){return y(D($b,d,f))}),w=new r(function(){return y(D(ac,e,k))}),z=new r(function(){var a=
new r(function(){return x(x(e).h)});return y(C(b,function(b){var d=new r(function(){return y(C(c,function(c){c=ka(x(bc),new g(1,b));return 19<G?new t(function(){return ga(a,k,b,c)}):(++G,ga(a,k,b,c))}))});return 19<G?new t(function(){return D(R,d,m)}):(++G,D(R,d,m))}))});return 19<G?new t(function(){return D(R,z,n)}):(++G,D(R,z,n))}var dc=new r(function(){return alert});function ec(a,c){var b=new FileReader;b.readAsDataURL(document.getElementById(a).files[0]);b.onload=function(){c(b.result)}}
var fc=new r(function(){return J("adPic")}),gc=new r(function(){return J("base")}),hc=new r(function(){return J("Control.Exception.Base")}),ic=new r(function(){return J("PatternMatchFail")});function jc(a){return x(new aa(new N(18445595,3739165398,!0),new N(52003073,3246954884,!0),new ba(new N(18445595,3739165398,!0),new N(52003073,3246954884,!0),gc,hc,ic),p))}function kc(a,c){return X(x(a).f,c)}
var mc=new r(function(){return new aa(jc,new l(function(a,c,b){return X(x(c).f,b)},function(a){return x(x(a).f)},function(a,c){return Ab(kc,a,c)}),lc,function(a){a=x(a);return ab(x(x(a.f).f),jc,a.h)})});function lc(a){return new h(0,mc,a)}var nc=new r(function(){return J("Non-exhaustive patterns in")});function oc(a){var c=lc;return ia(new r(function(){return y(C(c,a))}))}
function pc(a,c){var b=x(c);if(b.g){var d=b.f;if(y(C(a,d))){var e=new r(function(){var c=pc(a,b.h);return new h(0,c.f,c.h)});return new h(0,new h(1,d,new r(function(){return x(x(e).f)})),new r(function(){return x(x(e).h)}))}return new h(0,p,b)}return new h(0,p,p)}function qc(a){return 124==x(a)?!1:!0}
function rc(a){function c(a,b){return X(a,new r(function(){return K(": ",new r(function(){return X(nc,new r(function(){return X(b,new h(1,10,p))},1))}))},1))}var b=pc(qc,J(a));a=b.f;b=x(b.h);return b.g?124==x(b.f)?c(a,new h(1,32,b.h)):c(a,p):c(a,p)}function sc(a){return oc(new g(0,new r(function(){return rc(a)})))}
var tc=new r(function(){return sc("ads_apply.hs:(46,1)-(48,44)|function onCaptchaVerified")}),uc=new r(function(){return J("Internal Error!")}),vc=new r(function(){return J("\u9a8c\u8bc1\u7801\u9519\u8bef")}),wc=new r(function(){return sc("ads_apply.hs:31:1-39|function onSubmitResultReturn")});function xc(a,c){var b=x(a);return b.g?(x(dc)(H(x(b.f))),0):x(wc)}function Z(a,c){return a[c].toString()}
var yc=new r(function(){return J("ownerType")}),zc=new r(function(){return J("isJoined")}),Ac=new r(function(){return J("captcha")}),Bc=new r(function(){return J("/api/advertisement/insertApplication")}),Cc=new r(function(){return J("value")}),Dc=new r(function(){return J("ownerName")}),Ec=new r(function(){return J("ownerContact")}),Fc=new r(function(){return J(" found!")});function Gc(a){return ja(K("No element with ID ",new r(function(){return X(L(x(a)),Fc)})))}
function Hc(a,c){function b(a,c){var d=x(a);if(d.g){var e=x(d.f),f=H(e),n=document.getElementById(f);if(x(n===k))return Gc(f);var q=Z(n,H(m)),d=b(d.h,c);return new h(1,new h(0,e,new r(function(){return L(String(q))})),d)}return p}var d=x(Dc),e=H(d),f=document.getElementById(e),k=x(Ma);if(x(f===k))return Gc(e);var m=x(Cc),n=Z(f,H(m)),e=function(a,c,d){a=x(a);var e=H(a),f=document.getElementById(e);if(x(f===k))return Gc(e);var n=Z(f,H(m));c=b(c,d);return new h(1,new h(0,a,new r(function(){return L(String(n))})),
c)}(Ec,new h(1,yc,new h(1,zc,new h(1,Ac,p))),c);y(v(Zb,[Y,Ob,Ob,Ob,1,Bc,new h(1,new h(0,fc,new r(function(){var b=String(x(a));return L(b)})),new h(1,new h(0,d,new r(function(){return L(String(n))})),e)),xc,c]));return k}function Ic(a,c){var b=x(a);if(b.g)if(b=x(b.f),b.g){var d=b.h;switch(x(b.f)){case 48:if(x(d).g)return x(tc);x(dc)(H(x(vc)));return 0;case 49:if(x(d).g)return x(tc);b=Na(Hc);ec(H(x(fc)),b);return 0;default:return x(tc)}}else return x(tc);else return x(dc)(H(x(uc))),0}
var Jc=new h(0,function(a){switch(x(a)){case 0:return"load";case 1:return"unload";case 2:return"change";case 3:return"focus";case 4:return"blur";case 5:return"submit";default:return"scroll"}},function(a,c,b){return 0});function Kc(a,c){for(;;){var b=x(a);if(b.g){var d=x(c);if(d.g){if(x(b.f)!=x(d.f))return!1;a=b.h;c=d.h}else return!1}else return 0==x(c).g?!0:!1}}
function Lc(a){var c=x(new h(1,new h(0,Dc,Mc),new h(1,new h(0,Ec,Nc),new h(1,new h(0,Ac,Oc),p))));if(c.g){var b=x(c.f),d=b.h,b=H(x(b.f)),e=document.getElementById(b),f=x(Ma);x(e===f)?Gc(b):(y(v(cc,[Qb,Y,Pb,Lb,Jc,e,3,function(a,b){var c=x(Cc),f=Z(e,H(c));Kc(L(String(f)),d)&&(c=H(c),f=H(p),e[c]=f);return 0},a])),y(v(cc,[Qb,Y,Pb,Lb,Jc,e,4,function(a,b){var c=x(Cc),f=Z(e,H(c));L(String(f)).g||(c=H(c),f=H(x(d)),e[c]=f);return 0},a])),function(a,b){for(;;){var c=function(b,c){var d=x(b);if(d.g){var e=x(d.f),
m=e.h,e=H(x(e.f)),n=document.getElementById(e);if(x(n===f))return Gc(e);y(v(cc,[Qb,Y,Pb,Lb,Jc,n,3,function(a,b){var c=x(Cc),d=Z(n,H(c));Kc(L(String(d)),m)&&(c=H(c),d=H(p),n[c]=d);return 0},c]));y(v(cc,[Qb,Y,Pb,Lb,Jc,n,4,function(a,b){var c=x(Cc),d=Z(n,H(c));L(String(d)).g||(c=H(c),d=H(x(m)),n[c]=d);return 0},c]));a=d.h;return fa}return 0}(a,b);if(c!=fa)return c}}(c.h,a))}}
var Mc=new r(function(){return J("\u7533\u8bf7\u4eba\u59d3\u540d...")}),Nc=new r(function(){return J("\u8054\u7cfb\u65b9\u5f0f...")}),Oc=new r(function(){return J("\u8ba1\u7b97\u4e24\u6570\u76f8\u4e58\u7ed3\u679c...")});
function Pc(a){Lc(a);var c=document.getElementById("btn_submit"),b=x(Ma);if(x(c===b))return Gc("btn_submit");y(v(cc,[Qb,Y,Pb,Lb,new h(0,Kb,Jb),c,0,function(a,c){var f=H(x(Ac)),k=document.getElementById(f);if(x(k===b))return Gc(f);var m=Z(k,H(x(Cc)));y(v(Zb,[Y,Mb,Mb,Ob,0,new r(function(){return K("/api/captcha/verify?code=",new r(function(){return L(String(m))}))}),p,Ic,c]));return 0},a]));return 0}function Qc(a){return Pc(a)}window.onload=function(){y(v(Qc,[0]))};
