/*
 long.js (c) 2013 Daniel Wirtz <dcode@dcode.io>
 Released under the Apache License, Version 2.0
 see: https://github.com/dcodeIO/long.js for details
*/
function g(a,c){this.h=a;this.f=c}function h(a,c,b){this.h=a;this.f=c;this.i=b}function l(a,c,b){this.h=0;this.f=a;this.i=c;this.G=b}function aa(a,c,b,d){this.h=0;this.f=a;this.i=c;this.G=b;this.d=d}function ba(a,c,b,d,e){this.h=0;this.f=a;this.i=c;this.G=b;this.d=d;this.e=e}function ca(a){var c=n,b=n,d=n,e=n;this.h=0;this.f=c;this.i=7;this.G=b;this.d=a;this.e=d;this.l=e}function q(a,c){this.l=a;void 0===c&&(this.x=da)}function r(a){this.l=a}
function t(a,c){this.l=a;this.D=c;this.arity=a.length-c.length}var n=new function(a){this.h=a}(0),ea={},da={};
function v(a,c){for(;;)if(a=x(a),a instanceof Function){if(c.length===a.length)return a.apply(null,c);if(c.length<a.length)return new t(a,c);var b=a.apply(null,c.slice(0,a.length));c=c.slice(a.length);a=y(b)}else if(a instanceof t){if(c.length===a.arity)return a.l.apply(null,a.D.concat(c));if(c.length<a.arity)return new t(a.l,a.D.concat(c));b=a.l.apply(null,a.D.concat(c.slice(0,a.arity)));c=c.slice(a.arity);a=y(b)}else return a}
function C(a,c){a=x(a);return a instanceof Function?1===a.length?a(c):new t(a,[c]):a instanceof t?1===a.arity?a.l.apply(null,a.D.concat([c])):new t(a.l,a.D.concat([c])):a}
function D(a,c,b){a=x(a);if(a instanceof Function)switch(a.length){case 2:return a(c,b);case 1:return C(y(a(c)),b);default:return new t(a,[c,b])}else if(a instanceof t)switch(a.arity){case 2:return a.l.apply(null,a.D.concat([c,b]));case 1:return C(y(a.l.apply(null,a.D.concat([c]))),b);default:return new t(a.l,a.D.concat([c,b]))}else return a}
function fa(a,c,b,d){a=x(a);if(a instanceof Function)switch(a.length){case 3:return a(c,b,d);case 2:return C(y(a(c,b)),d);case 1:return D(y(a(c)),b,d);default:return new t(a,[c,b,d])}else if(a instanceof t)switch(a.arity){case 3:return a.l.apply(null,a.D.concat([c,b,d]));case 2:return C(y(a.l.apply(null,a.D.concat([c,b]))),d);case 1:return D(y(a.l.apply(null,a.D.concat([c]))),b,d);default:return new t(a.l,a.D.concat([c,b,d]))}else return a}
function x(a){if(a instanceof q){if(a.l!==ea)if(a.x===da){var c=a.l;a.l=ea;a.x=c()}else return a.l();if(a.x===da)throw"Infinite loop!";return a.x}return a}var F=0,ga=[];function y(a){for(ga.push(F);a instanceof r;){var c=a.l;a.l=ea;F=0;a=c()}F=ga.pop();return a}if(!window)var window={};window.Haste={};window.A=v;window.E=x;window.B=y;function ha(a){throw x(a);}function ia(a){ha(G(a))}function I(a){return J(a,n)}
function J(a,c,b){var d=b?b:0;return d>=a.length?x(c):{h:1,f:a.charCodeAt(d),i:new q(function(){return J(a,c,d+1)})}}function K(a){return I(x(a))}function G(a){var c="";for(a=x(a);1==a.h;a=x(a.i))c+=String.fromCharCode(x(a.f));return c}function ja(a,c){a.x=c}var ka=Math.trunc?Math.trunc:function(a){return 0>a?Math.ceil(a):Math.floor(a)};if("undefined"==typeof la)var la=void 0;var ma=new ArrayBuffer(8);new Uint32Array(ma);new Float32Array(ma);new Float64Array(ma);
window.jsGetMouseCoords=function(a){var c=0,b=0;a||(a=window.event);if(a.pageX||a.pageY)c=a.pageX,b=a.pageY;else if(a.clientX||a.clientY)c=a.clientX+document.body.scrollLeft+document.documentElement.scrollLeft,b=a.clientY+document.body.scrollTop+document.documentElement.scrollTop;return[c-(a.currentTarget.offsetLeft||0),b-(a.currentTarget.offsetTop||0)]};function na(a,c){var b=[];for(a=x(a);a.h;)a=x(a),b.push(x(a.f)),a=x(a.i);return b.join(c)}
function oa(a,c,b){c=new ArrayBuffer(c);(new window[a](c))[0]=b;return c}function pa(a,c,b){var d=new ArrayBuffer(c);(new window[a](d))[0]=b;a=new Uint8Array(d);b=0;for(c=c-1;b<c;++b,--c){var e=a[b];a[b]=a[c];a[c]=e}return d}window.toABle=oa;window.toABbe=pa;var qa=new ArrayBuffer(2);(new DataView(qa)).setInt16(0,256,!0);256!==(new Int16Array(qa))[0]&&(window.toABle=pa,window.toABbe=oa);var L={};
(function(a,c){function b(a,b,c){if(null!==a&&"object"===typeof a&&Array.isArray(a.a))return a;this.c=0;this.a=null;this.length=0;if("le"===b||"be"===b)c=b,b=10;null!==a&&this.ja(a||0,b||10,c||"be")}function d(a,b,c){var d=0;for(c=Math.min(a.length,c);b<c;b++)var e=a.charCodeAt(b)-48,d=d<<4,d=49<=e&&54>=e?d|e-49+10:17<=e&&22>=e?d|e-17+10:d|e&15;return d}function e(a,b,c,d){var e=0;for(c=Math.min(a.length,c);b<c;b++)var f=a.charCodeAt(b)-48,e=e*d,e=49<=f?e+(f-49+10):17<=f?e+(f-17+10):e+f;return e}
"object"===typeof a?a.Ra=b:c.M=b;b.M=b;b.$=26;b.max=function(a,b){return 0<a.N(b)?a:b};b.min=function(a,b){return 0>a.N(b)?a:b};b.prototype.ja=function(a,b,c){if("number"===typeof a)this.ka(a,b,c);else if("object"===typeof a)this.T(a,b,c);else{"hex"===b&&(b=16);a=a.toString().replace(/\s+/g,"");var d=0;"-"===a[0]&&d++;16===b?this.ma(a,d):this.la(a,b,d);"-"===a[0]&&(this.c=1);this.u();"le"===c&&this.T(this.ia(),b,c)}};b.prototype.ka=function(a,b,c){0>a&&(this.c=1,a=-a);67108864>a?(this.a=[a&67108863],
this.length=1):4503599627370496>a?(this.a=[a&67108863,a/67108864&67108863],this.length=2):(this.a=[a&67108863,a/67108864&67108863,1],this.length=3);"le"===c&&this.T(this.ia(),b,c)};b.prototype.T=function(a,b,c){if(0>=a.length)this.a=[0],this.length=1;else{this.length=Math.ceil(a.length/3);this.a=Array(this.length);for(b=0;b<this.length;b++)this.a[b]=0;var d=0;if("be"===c)for(b=a.length-1,c=0;0<=b;b-=3){var e=a[b]|a[b-1]<<8|a[b-2]<<16;this.a[c]|=e<<d&67108863;this.a[c+1]=e>>>26-d&67108863;d+=24;26<=
d&&(d-=26,c++)}else if("le"===c)for(c=b=0;b<a.length;b+=3)e=a[b]|a[b+1]<<8|a[b+2]<<16,this.a[c]|=e<<d&67108863,this.a[c+1]=e>>>26-d&67108863,d+=24,26<=d&&(d-=26,c++);this.u()}};b.prototype.ma=function(a,b){this.length=Math.ceil((a.length-b)/6);this.a=Array(this.length);for(var c=0;c<this.length;c++)this.a[c]=0;for(var e=0,c=a.length-6,f=0;c>=b;c-=6){var w=d(a,c,c+6);this.a[f]|=w<<e&67108863;this.a[f+1]|=w>>>26-e&4194303;e+=24;26<=e&&(e-=26,f++)}c+6!==b&&(w=d(a,b,c+6),this.a[f]|=w<<e&67108863,this.a[f+
1]|=w>>>26-e&4194303);this.u()};b.prototype.la=function(a,b,c){this.a=[0];this.length=1;for(var d=0,f=1;67108863>=f;f*=b)d++;d--;for(var f=f/b|0,w=a.length-c,k=w%d,p=Math.min(w,w-k)+c,w=0;c<p;c+=d)w=e(a,c,c+d,b),this.ca(f),67108864>this.a[0]+w?this.a[0]+=w:this.Y(w);if(0!==k){d=1;w=e(a,c,a.length,b);for(c=0;c<k;c++)d*=b;this.ca(d);67108864>this.a[0]+w?this.a[0]+=w:this.Y(w)}};b.prototype.ra=function(a){a.a=Array(this.length);for(var b=0;b<this.length;b++)a.a[b]=this.a[b];a.length=this.length;a.c=
this.c};b.prototype.clone=function(){var a=new b(null);this.ra(a);return a};b.prototype.u=function(){for(;1<this.length&&0===this.a[this.length-1];)this.length--;return this.J()};b.prototype.J=function(){1===this.length&&0===this.a[0]&&(this.c=0);return this};var f=" 0 00 000 0000 00000 000000 0000000 00000000 000000000 0000000000 00000000000 000000000000 0000000000000 00000000000000 000000000000000 0000000000000000 00000000000000000 000000000000000000 0000000000000000000 00000000000000000000 000000000000000000000 0000000000000000000000 00000000000000000000000 000000000000000000000000 0000000000000000000000000".split(" "),
k=[0,0,25,16,12,11,10,9,8,8,7,7,7,7,6,6,6,6,6,6,6,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5],m=[0,0,33554432,43046721,16777216,48828125,60466176,40353607,16777216,43046721,1E7,19487171,35831808,62748517,7529536,11390625,16777216,24137569,34012224,47045881,64E6,4084101,5153632,6436343,7962624,9765625,11881376,14348907,17210368,20511149,243E5,28629151,33554432,39135393,45435424,52521875,60466176];b.prototype.toString=function(a,b){a=a||10;b=b|0||1;if(16===a||"hex"===a){for(var c="",d=0,e=0,w=0;w<this.length;w++){var M=
this.a[w],p=((M<<d|e)&16777215).toString(16),e=M>>>24-d&16777215,c=0!==e||w!==this.length-1?f[6-p.length]+p+c:p+c,d=d+2;26<=d&&(d-=26,w--)}for(0!==e&&(c=e.toString(16)+c);0!==c.length%b;)c="0"+c;0!==this.c&&(c="-"+c);return c}if(a===(a|0)&&2<=a&&36>=a){d=k[a];e=m[a];c="";w=this.clone();for(w.c=0;0!==w.I();)M=w.W(e).toString(a),w=w.ba(e),c=0!==w.I()?f[d-M.length]+M+c:M+c;for(0===this.I()&&(c="0"+c);0!==c.length%b;)c="0"+c;0!==this.c&&(c="-"+c);return c}throw"Base should be between 2 and 36";};b.prototype.toJSON=
function(){return this.toString(16)};b.prototype.ia=function(){this.u();var a=Array(this.byteLength());a[0]=0;for(var b=this.clone(),c=0;0!==b.I();c++){var d=b.oa();b.fa(8);a[a.length-c-1]=d}return a};b.prototype.X=Math.qa?function(a){return 32-Math.qa(a)}:function(a){var b=0;4096<=a&&(b+=13,a>>>=13);64<=a&&(b+=7,a>>>=7);8<=a&&(b+=4,a>>>=4);2<=a&&(b+=2,a>>>=2);return b+a};b.prototype.pa=function(){var a=0,a=this.X(this.a[this.length-1]);return 26*(this.length-1)+a};b.prototype.byteLength=function(){return Math.ceil(this.pa()/
8)};b.prototype.o=function(){if(0===this.I())return this.clone();var a=this.clone();a.c=this.c^1;return a};b.prototype.ya=function(a){for(;this.length<a.length;)this.a[this.length++]=0;for(var b=0;b<a.length;b++)this.a[b]|=a.a[b];return this.u()};b.prototype.da=function(a){return this.ya(a)};b.prototype.Ca=function(a){return this.length>a.length?this.clone().da(a):a.clone().da(this)};b.prototype.xa=function(a){var b;b=this.length>a.length?a:this;for(var c=0;c<b.length;c++)this.a[c]&=a.a[c];this.length=
b.length;return this.u()};b.prototype.aa=function(a){return this.xa(a)};b.prototype.ua=function(a){return this.length>a.length?this.clone().aa(a):a.clone().aa(this)};b.prototype.za=function(a){var b;this.length>a.length?b=this:(b=a,a=this);for(var c=0;c<a.length;c++)this.a[c]=b.a[c]^a.a[c];if(this!==b)for(;c<b.length;c++)this.a[c]=b.a[c];this.length=b.length;return this.u()};b.prototype.ga=function(a){return this.za(a)};b.prototype.Ga=function(a){return this.length>a.length?this.clone().ga(a):a.clone().ga(this)};
b.prototype.P=function(a){if(0!==this.c&&0===a.c){this.c=0;var b=this.R(a);this.c^=1;return this.J()}if(0===this.c&&0!==a.c)return a.c=0,b=this.R(a),a.c=1,b.J();var c;this.length>a.length?c=this:(c=a,a=this);for(var d=b=0;d<a.length;d++)b=(c.a[d]|0)+(a.a[d]|0)+b,this.a[d]=b&67108863,b>>>=26;for(;0!==b&&d<c.length;d++)b=(c.a[d]|0)+b,this.a[d]=b&67108863,b>>>=26;this.length=c.length;if(0!==b)this.a[this.length]=b,this.length++;else if(c!==this)for(;d<c.length;d++)this.a[d]=c.a[d];return this};b.prototype.add=
function(a){if(0!==a.c&&0===this.c){a.c=0;var b=this.sub(a);a.c^=1;return b}return 0===a.c&&0!==this.c?(this.c=0,b=a.sub(this),this.c=1,b):this.length>a.length?this.clone().P(a):a.clone().P(this)};b.prototype.R=function(a){if(0!==a.c){a.c=0;var b=this.P(a);a.c=1;return b.J()}if(0!==this.c)return this.c=0,this.P(a),this.c=1,this.J();b=this.N(a);if(0===b)return this.c=0,this.length=1,this.a[0]=0,this;var c;0<b?c=this:(c=a,a=this);for(var d=0,e=0;e<a.length;e++)b=(c.a[e]|0)-(a.a[e]|0)+d,d=b>>26,this.a[e]=
b&67108863;for(;0!==d&&e<c.length;e++)b=(c.a[e]|0)+d,d=b>>26,this.a[e]=b&67108863;if(0===d&&e<c.length&&c!==this)for(;e<c.length;e++)this.a[e]=c.a[e];this.length=Math.max(this.length,e);c!==this&&(this.c=1);return this.u()};b.prototype.sub=function(a){return this.clone().R(a)};b.prototype.Da=function(a,b){if(63>this.length+a.length){b.c=a.c^this.c;var c=this.length+a.length|0;b.length=c;var c=c-1|0,d=this.a[0]|0,e=a.a[0]|0,d=d*e,f=d/67108864|0;b.a[0]=d&67108863;for(var k=1;k<c;k++){for(var p=f>>>
26,f=f&67108863,m=Math.min(k,a.length-1),T=Math.max(0,k-this.length+1);T<=m;T++)d=this.a[k-T|0]|0,e=a.a[T]|0,d*=e,e=d&67108863,p=p+(d/67108864|0)|0,e=e+f|0,f=e&67108863,p=p+(e>>>26)|0;b.a[k]=f|0;f=p|0}0!==f?b.a[k]=f|0:b.length--}else{b.c=a.c^this.c;b.length=this.length+a.length;for(k=c=f=0;k<b.length-1;k++){p=c;c=0;f&=67108863;m=Math.min(k,a.length-1);for(T=Math.max(0,k-this.length+1);T<=m;T++)d=(this.a[k-T]|0)*(a.a[T]|0),e=d&67108863,p=p+(d/67108864|0)|0,e=e+f|0,f=e&67108863,p=p+(e>>>26)|0,c+=p>>>
26,p&=67108863;b.a[k]=f;f=p}0!==f?b.a[k]=f:b.length--}return b.u()};b.prototype.H=function(a){var c=new b(null);c.a=Array(this.length+a.length);return this.Da(a,c)};b.prototype.ca=function(a){for(var b=0,c=0;c<this.length;c++){var d=(this.a[c]|0)*a,e=(d&67108863)+(b&67108863),b=b>>26,b=b+(d/67108864|0),b=b+(e>>>26);this.a[c]=e&67108863}0!==b&&(this.a[c]=b,this.length++)};b.prototype.ea=function(a){var b=a%26;a=(a-b)/26;var c=67108863>>>26-b<<26-b;if(0!==b){for(var d=0,e=0;e<this.length;e++){var f=
this.a[e]&c;this.a[e]=(this.a[e]|0)-f<<b|d;d=f>>>26-b}d&&(this.a[e]=d,this.length++)}if(0!==a){for(e=this.length-1;0<=e;e--)this.a[e+a]=this.a[e];for(e=0;e<a;e++)this.a[e]=0;this.length+=a}return this.u()};b.prototype.fa=function(a){var b;b=0;var c=a%26,d=Math.min((a-c)/26,this.length),e=67108863^67108863>>>c<<c;b=Math.max(0,b-d);if(0!==d)if(this.length>d)for(this.length-=d,a=0;a<this.length;a++)this.a[a]=this.a[a+d];else this.a[0]=0,this.length=1;d=0;for(a=this.length-1;0<=a&&(0!==d||a>=b);a--){var f=
this.a[a]|0;this.a[a]=d<<26-c|f>>>c;d=f&e}0===this.length&&(this.a[0]=0,this.length=1);this.u()};b.prototype.Ka=function(a){return this.clone().ea(a)};b.prototype.Y=function(a){this.a[0]+=a;for(a=0;a<this.length&&67108864<=this.a[a];a++)this.a[a]-=67108864,a===this.length-1?this.a[a+1]=1:this.a[a+1]++;this.length=Math.max(this.length,a+1)};b.prototype.wa=function(){this.c=0;return this};b.prototype.abs=function(){return this.clone().wa()};b.prototype.U=function(a,b,c){var d=a.length+c,e;if(this.a.length<
d){var f=Array(d);for(e=0;e<this.length;e++)f[e]=this.a[e];this.a=f}else e=this.length;for(this.length=Math.max(this.length,d);e<this.length;e++)this.a[e]=0;for(e=f=0;e<a.length;e++)d=(this.a[e+c]|0)+f,f=(a.a[e]|0)*b,d-=f&67108863,f=(d>>26)-(f/67108864|0),this.a[e+c]=d&67108863;for(;e<this.length-c;e++)d=(this.a[e+c]|0)+f,f=d>>26,this.a[e+c]=d&67108863;if(0===f)return this.u();for(e=f=0;e<this.length;e++)d=-(this.a[e]|0)+f,f=d>>26,this.a[e]=d&67108863;this.c=1;return this.u()};b.prototype.na=function(a,
c){var d=this.length-a.length,e=this.clone(),f=a,k=f.a[f.length-1]|0,d=26-this.X(k);0!==d&&(f=f.Ka(d),e.ea(d),k=f.a[f.length-1]|0);var m=e.length-f.length,p;if("mod"!==c){p=new b(null);p.length=m+1;p.a=Array(p.length);for(var O=0;O<p.length;O++)p.a[O]=0}O=e.clone().U(f,1,m);0===O.c&&(e=O,p&&(p.a[m]=1));for(--m;0<=m;m--){O=67108864*(e.a[f.length+m]|0)+(e.a[f.length+m-1]|0);O=Math.min(O/k|0,67108863);for(e.U(f,O,m);0!==e.c;)O--,e.c=0,e.U(f,1,m),0!==e.I()&&(e.c^=1);p&&(p.a[m]=O)}p&&p.u();e.u();"div"!==
c&&0!==d&&e.fa(d);return{s:p?p:null,C:e}};b.prototype.K=function(a,c,d){if(0!==this.c&&0===a.c){var e=this.o().K(a,c),f,k;"mod"!==c&&(f=e.s.o());"div"!==c&&(k=e.C.o(),d&&k.o&&(k=k.add(a)));return{s:f,C:k}}return 0===this.c&&0!==a.c?(e=this.K(a.o(),c),"mod"!==c&&(f=e.s.o()),{s:f,C:e.C}):0!==(this.c&a.c)?(e=this.o().K(a.o(),c),"div"!==c&&(k=e.C.o(),d&&k.o&&(k=k.R(a))),{s:e.s,C:k}):a.length>this.length||0>this.N(a)?{s:new b(0),C:this}:1===a.length?"div"===c?{s:this.Z(a.a[0]),C:null}:"mod"===c?{s:null,
C:new b(this.W(a.a[0]))}:{s:this.Z(a.a[0]),C:new b(this.W(a.a[0]))}:this.na(a,c)};b.prototype.s=function(a){return this.K(a,"div",!1).s};b.prototype.C=function(a){return this.K(a,"mod",!1).C};b.prototype.W=function(a){for(var b=67108864%a,c=0,d=this.length-1;0<=d;d--)c=(b*c+(this.a[d]|0))%a;return c};b.prototype.ba=function(a){for(var b=0,c=this.length-1;0<=c;c--)b=(this.a[c]|0)+67108864*b,this.a[c]=b/a|0,b%=a;return this.u()};b.prototype.Z=function(a){return this.clone().ba(a)};b.prototype.V=function(){return 1===
(this.a[0]&1)};b.prototype.oa=function(){return this.a[0]&255};b.prototype.I=function(){var a=0,b=0>a;b&&(a=-a);if(0!==this.c&&!b)return-1;if(0===this.c&&b)return 1;a&=67108863;this.u();1<this.length?a=1:(b=this.a[0]|0,a=b===a?0:b<a?-1:1);0!==this.c&&(a=-a);return a};b.prototype.N=function(a){if(0!==this.c&&0===a.c)return-1;if(0===this.c&&0!==a.c)return 1;a=this.Ja(a);return 0!==this.c?-a:a};b.prototype.Ja=function(a){if(this.length>a.length)return 1;if(this.length<a.length)return-1;for(var b=0,c=
this.length-1;0<=c;c--){var d=this.a[c]|0,e=a.a[c]|0;if(d!==e){d<e?b=-1:d>e&&(b=1);break}}return b}})(void 0,L);L.Qa=new L.M(0);L.ONE=new L.M(1);L.Pa=new L.M(4294967296);function N(a,c,b){this.j=a|0;this.g=c|0;this.m=!!b}var ra={},sa={};function ta(a,c){return c?0<=(a>>>=0)&&256>a:-128<=(a|=0)&&128>a}function P(a,c){var b,d;if(c){if(d=ta(a>>>=0,!0))if(b=sa[a])return b;b=new N(a,0>(a|0)?-1:0,!0);d&&(sa[a]=b)}else{if(d=ta(a|=0,!1))if(b=ra[a])return b;b=new N(a,0>a?-1:0,!1);d&&(ra[a]=b)}return b}
function ua(a,c){if(isNaN(a)||!isFinite(a))return c?wa:R;if(c){if(0>a)return wa;if(a>=xa)return ya}else{if(a<=-za)return S;if(a+1>=za)return Aa}return 0>a?ua(-a,c).o():new N(a%Ba|0,a/Ba|0,c)}var Ca=Math.pow,Ba=4294967296,xa=Ba*Ba,za=xa/2,Da=P(16777216),R=P(0),wa=P(0,!0),Ea=P(1);P(1,!0);var Fa=P(-1),Aa=new N(-1,2147483647,!1),ya=new N(-1,-1,!0),S=new N(0,-2147483648,!1),U=N.prototype;U.Ma=function(){return this.m?this.j>>>0:this.j};
U.S=function(){return this.m?(this.g>>>0)*Ba+(this.j>>>0):this.g*Ba+(this.j>>>0)};U.L=function(){return 0===this.g&&0===this.j};U.F=function(){return!this.m&&0>this.g};U.V=function(){return 1===(this.j&1)};U.w=function(a){return this.m!==a.m&&1===this.g>>>31&&1===a.g>>>31?!1:this.g===a.g&&this.j===a.j};U.Ta=function(a){return!this.w(a)};U.ha=function(){return 0>this.O(Da)};U.Sa=function(a){return 0>=this.O(a)};U.sa=function(a){return 0<this.O(a)};U.ta=function(a){return 0<=this.O(a)};
U.$=function(a){if(this.w(a))return 0;var c=this.F(),b=a.F();return c&&!b?-1:!c&&b?1:this.m?a.g>>>0>this.g>>>0||a.g===this.g&&a.j>>>0>this.j>>>0?-1:1:this.sub(a).F()?-1:1};U.O=U.$;U.Ba=function(){return!this.m&&this.w(S)?S:this.Ea().add(Ea)};U.o=U.Ba;
U.add=function(a){var c=this.g>>>16,b=this.g&65535,d=this.j>>>16,e=a.g>>>16,f=a.g&65535,k=a.j>>>16,m;m=0+((this.j&65535)+(a.j&65535));a=0+(m>>>16);a+=d+k;d=0+(a>>>16);d+=b+f;b=0+(d>>>16);b=b+(c+e)&65535;return new N((a&65535)<<16|m&65535,b<<16|d&65535,this.m)};U.Fa=function(a){return this.add(a.o())};U.sub=U.Fa;
U.multiply=function(a){if(this.L()||a.L())return R;if(this.w(S))return a.V()?S:R;if(a.w(S))return this.V()?S:R;if(this.F())return a.F()?this.o().H(a.o()):this.o().H(a).o();if(a.F())return this.H(a.o()).o();if(this.ha()&&a.ha())return ua(this.S()*a.S(),this.m);var c=this.g>>>16,b=this.g&65535,d=this.j>>>16,e=this.j&65535,f=a.g>>>16,k=a.g&65535,m=a.j>>>16;a=a.j&65535;var u,z,H,Q;Q=0+e*a;H=0+(Q>>>16);H+=d*a;z=0+(H>>>16);H=(H&65535)+e*m;z+=H>>>16;H&=65535;z+=b*a;u=0+(z>>>16);z=(z&65535)+d*m;u+=z>>>16;
z&=65535;z+=e*k;u+=z>>>16;z&=65535;u=u+(c*a+b*m+d*k+e*f)&65535;return new N(H<<16|Q&65535,u<<16|z,this.m)};U.H=U.multiply;
U.va=function(a){if(a.L())throw Error("division by zero");if(this.L())return this.m?wa:R;var c,b,d;if(this.w(S)){if(a.w(Ea)||a.w(Fa))return S;if(a.w(S))return Ea;c=this.Ia().s(a).Ha();if(c.w(R))return a.F()?Ea:Fa;b=this.sub(a.H(c));return d=c.add(b.s(a))}if(a.w(S))return this.m?wa:R;if(this.F())return a.F()?this.o().s(a.o()):this.o().s(a).o();if(a.F())return this.s(a.o()).o();d=R;for(b=this;b.ta(a);){c=Math.max(1,Math.floor(b.S()/a.S()));for(var e=Math.ceil(Math.log(c)/Math.LN2),e=48>=e?1:Ca(2,e-
48),f=ua(c),k=f.H(a);k.F()||k.sa(b);)c-=e,f=ua(c,this.m),k=f.H(a);f.L()&&(f=Ea);d=d.add(f);b=b.sub(k)}return d};U.s=U.va;U.Aa=function(a){return this.sub(this.s(a).H(a))};U.C=U.Aa;U.Ea=function(){return new N(~this.j,~this.g,this.m)};U.ua=function(a){return new N(this.j&a.j,this.g&a.g,this.m)};U.Ca=function(a){return new N(this.j|a.j,this.g|a.g,this.m)};U.Ga=function(a){return new N(this.j^a.j,this.g^a.g,this.m)};
U.Ha=function(){var a=1;return 0===(a&=63)?this:32>a?new N(this.j<<a,this.g<<a|this.j>>>32-a,this.m):new N(0,this.j<<a-32,this.m)};U.Ia=function(){var a=1;return 0===(a&=63)?this:32>a?new N(this.j>>>a|this.g<<32-a,this.g>>a,this.m):new N(this.g>>a-32,0<=this.g?0:-1,this.m)};U.La=function(a){a&=63;if(0===a)return this;var c=this.g;return 32>a?new N(this.j>>>a|c<<32-a,c>>>a,this.m):32===a?new N(c,0,this.m):new N(c>>>a-32,0,this.m)};U.Na=function(){return this.m?new N(this.j,this.g,!1):this};
U.Oa=function(){return this.m?this:new N(this.j,this.g,!0)};
function Ga(a,c){var b=a[0],d=a[1],e=a[2],f=a[3],b=V(b,d,e,f,c[0],7,-680876936),f=V(f,b,d,e,c[1],12,-389564586),e=V(e,f,b,d,c[2],17,606105819),d=V(d,e,f,b,c[3],22,-1044525330),b=V(b,d,e,f,c[4],7,-176418897),f=V(f,b,d,e,c[5],12,1200080426),e=V(e,f,b,d,c[6],17,-1473231341),d=V(d,e,f,b,c[7],22,-45705983),b=V(b,d,e,f,c[8],7,1770035416),f=V(f,b,d,e,c[9],12,-1958414417),e=V(e,f,b,d,c[10],17,-42063),d=V(d,e,f,b,c[11],22,-1990404162),b=V(b,d,e,f,c[12],7,1804603682),f=V(f,b,d,e,c[13],12,-40341101),e=V(e,f,
b,d,c[14],17,-1502002290),d=V(d,e,f,b,c[15],22,1236535329),b=W(b,d,e,f,c[1],5,-165796510),f=W(f,b,d,e,c[6],9,-1069501632),e=W(e,f,b,d,c[11],14,643717713),d=W(d,e,f,b,c[0],20,-373897302),b=W(b,d,e,f,c[5],5,-701558691),f=W(f,b,d,e,c[10],9,38016083),e=W(e,f,b,d,c[15],14,-660478335),d=W(d,e,f,b,c[4],20,-405537848),b=W(b,d,e,f,c[9],5,568446438),f=W(f,b,d,e,c[14],9,-1019803690),e=W(e,f,b,d,c[3],14,-187363961),d=W(d,e,f,b,c[8],20,1163531501),b=W(b,d,e,f,c[13],5,-1444681467),f=W(f,b,d,e,c[2],9,-51403784),
e=W(e,f,b,d,c[7],14,1735328473),d=W(d,e,f,b,c[12],20,-1926607734),b=X(d^e^f,b,d,c[5],4,-378558),f=X(b^d^e,f,b,c[8],11,-2022574463),e=X(f^b^d,e,f,c[11],16,1839030562),d=X(e^f^b,d,e,c[14],23,-35309556),b=X(d^e^f,b,d,c[1],4,-1530992060),f=X(b^d^e,f,b,c[4],11,1272893353),e=X(f^b^d,e,f,c[7],16,-155497632),d=X(e^f^b,d,e,c[10],23,-1094730640),b=X(d^e^f,b,d,c[13],4,681279174),f=X(b^d^e,f,b,c[0],11,-358537222),e=X(f^b^d,e,f,c[3],16,-722521979),d=X(e^f^b,d,e,c[6],23,76029189),b=X(d^e^f,b,d,c[9],4,-640364487),
f=X(b^d^e,f,b,c[12],11,-421815835),e=X(f^b^d,e,f,c[15],16,530742520),d=X(e^f^b,d,e,c[2],23,-995338651),b=Y(b,d,e,f,c[0],6,-198630844),f=Y(f,b,d,e,c[7],10,1126891415),e=Y(e,f,b,d,c[14],15,-1416354905),d=Y(d,e,f,b,c[5],21,-57434055),b=Y(b,d,e,f,c[12],6,1700485571),f=Y(f,b,d,e,c[3],10,-1894986606),e=Y(e,f,b,d,c[10],15,-1051523),d=Y(d,e,f,b,c[1],21,-2054922799),b=Y(b,d,e,f,c[8],6,1873313359),f=Y(f,b,d,e,c[15],10,-30611744),e=Y(e,f,b,d,c[6],15,-1560198380),d=Y(d,e,f,b,c[13],21,1309151649),b=Y(b,d,e,f,
c[4],6,-145523070),f=Y(f,b,d,e,c[11],10,-1120210379),e=Y(e,f,b,d,c[2],15,718787259),d=Y(d,e,f,b,c[9],21,-343485551);a[0]=b+a[0]&4294967295;a[1]=d+a[1]&4294967295;a[2]=e+a[2]&4294967295;a[3]=f+a[3]&4294967295}function X(a,c,b,d,e,f){c=(c+a&4294967295)+(d+f&4294967295)&4294967295;return(c<<e|c>>>32-e)+b&4294967295}function V(a,c,b,d,e,f,k){return X(c&b|~c&d,a,c,e,f,k)}function W(a,c,b,d,e,f,k){return X(c&d|b&~d,a,c,e,f,k)}function Y(a,c,b,d,e,f,k){return X(b^(c|~d),a,c,e,f,k)}
function Ha(a,c){var b=a.v.w8,d=c,e=[1732584193,-271733879,-1732584194,271733878],f;for(f=64;f<=c;f+=64){for(var k=b.subarray(f-64,f),m=[],u=void 0,u=0;64>u;u+=4)m[u>>2]=k[u]+(k[u+1]<<8)+(k[u+2]<<16)+(k[u+3]<<24);Ga(e,m)}b=b.subarray(f-64);c=c<f-64?0:c-(f-64);k=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];for(f=0;f<c;f++)k[f>>2]|=b[f]<<(f%4<<3);k[f>>2]|=128<<(f%4<<3);if(55<f)for(Ga(e,k),f=0;16>f;f++)k[f]=0;k[14]=8*d;Ga(e,k);return e}window.md51=Ha;var Ia="0123456789abcdef".split("");
window.md5=function(a,c){for(var b=Ha(a,c),d=0;d<b.length;d++){for(var e=b[d],f="",k=0;4>k;k++)f+=Ia[e>>8*k+4&15]+Ia[e>>8*k&15];b[d]=f}return b.join("")};window.newByteArr=function(a){var c=8-a%8;8>c&&(a+=c);c={};a=new ArrayBuffer(a);var b={};b.i8=new Int8Array(a);b.i16=new Int16Array(a);b.i32=new Int32Array(a);b.w8=new Uint8Array(a);b.w16=new Uint16Array(a);b.w32=new Uint32Array(a);b.f32=new Float32Array(a);b.f64=new Float64Array(a);c.b=a;c.v=b;c.off=0;return c};
function Ja(a){var c=x(Ka);return a===c}function La(a){return a instanceof Function&&2===a.length?function(){var c=a.apply(null,arguments);if(c instanceof q){if(c.l!==ea){var b=c.l;c.l=ea;return c.x=b()}return c.x}for(;c instanceof r;)c=c.l();return x(c)}:function(){var c=Array.prototype.slice.call(arguments);c.push(0);return x(y(v(a,c)))}}function Ma(a,c){return a>=c.length?n:{h:1,f:c[a],i:new q(function(){return Ma(a+1,c)})}}
function Z(a,c){var b=x(a);return 0==b.h?x(c):new h(1,b.f,new q(function(){return Z(b.i,c)}))}var Na=new q(function(){return J(") is outside of enumeration's range (0,",new q(function(){var a=new h(1,41,n);return Z(K((2).toString()),a)}))});function Oa(a){return ia(J("toEnum{MouseButton}: tag (",new q(function(){return Z(K(a.toString()),Na)})))}function Pa(a,c){return new q(function(){var b=Number(x(a)),b=ka(b);return 0>b?Oa(b):2<b?Oa(b):b})}var Qa=new l(0,0,0),Ra=new q(function(){return jsGetMouseCoords});
function Sa(a,c){var b=x(a);if(b.h){var d=Sa(b.i,c);return new h(1,new q(function(){var a=Number(x(b.f));return ka(a)}),d)}return n}var Ta=new h(0,function(a,c){return new q(function(){var b=Number(x(a));return ka(b)})},function(a,c){var b=x(a);return Sa(Ma(0,b),c)});function Ua(a,c){var b=x(a);if(b.h){var d=Ua(b.i,c);return new h(1,b.f,d)}return n}var Va=new q(function(){return I("base")}),Wa=new q(function(){return I("GHC.IO.Exception")}),Xa=new q(function(){return I("IOException")});
function Ya(a){return x(new aa(new N(4053623282,1685460941,!0),new N(3693590983,2507416641,!0),new ba(new N(4053623282,1685460941,!0),new N(3693590983,2507416641,!0),Va,Wa,Xa),n))}function Za(a,c,b){a=y(C(a,la));c=y(C(c,la));return x(a.f.w(c.f))?0==x(a.i.w(c.i))?n:new g(1,b):n}
var $a=new q(function(){return I(": ")}),ab=new q(function(){return I(" (")}),bb=new q(function(){return I("already exists")}),cb=new q(function(){return I("does not exist")}),db=new q(function(){return I("protocol error")}),eb=new q(function(){return I("failed")}),fb=new q(function(){return I("invalid argument")}),gb=new q(function(){return I("inappropriate type")}),hb=new q(function(){return I("hardware fault")}),ib=new q(function(){return I("unsupported operation")}),jb=new q(function(){return I("timeout")}),
kb=new q(function(){return I("resource vanished")}),lb=new q(function(){return I("interrupted")}),mb=new q(function(){return I("resource busy")}),nb=new q(function(){return I("resource exhausted")}),ob=new q(function(){return I("end of file")}),pb=new q(function(){return I("illegal operation")}),qb=new q(function(){return I("permission denied")}),rb=new q(function(){return I("user error")}),sb=new q(function(){return I("unsatisified constraints")}),tb=new q(function(){return I("system error")});
function ub(a,c){switch(x(a)){case 0:return Z(bb,c);case 1:return Z(cb,c);case 2:return Z(mb,c);case 3:return Z(nb,c);case 4:return Z(ob,c);case 5:return Z(pb,c);case 6:return Z(qb,c);case 7:return Z(rb,c);case 8:return Z(sb,c);case 9:return Z(tb,c);case 10:return Z(db,c);case 11:return Z(eb,c);case 12:return Z(fb,c);case 13:return Z(gb,c);case 14:return Z(hb,c);case 15:return Z(ib,c);case 16:return Z(jb,c);case 17:return Z(kb,c);default:return Z(lb,c)}}var vb=new q(function(){return I("{handle: ")});
function wb(a,c,b,d,e,f){var k=new q(function(){var a=new q(function(){return ub(c,new q(function(){var a=x(d);return a.h?Z(ab,new q(function(){return Z(a,new h(1,41,f))},1)):x(f)},1))},1),e=x(b);return e.h?Z(e,new q(function(){return Z($a,a)},1)):x(a)},1);e=x(e);if(e.h)return Z(e.f,new q(function(){return Z($a,k)},1));a=x(a);if(a.h){var m=x(a.f);return Z(vb,new q(function(){return Z(m.f,new h(1,125,new q(function(){return Z($a,k)})))},1))}return x(k)}
function xb(a,c){var b=x(a);return wb(b.f,b.i,b.G,b.d,b.l,c)}function yb(a,c,b){var d=x(c);return d.h?new h(1,91,new q(function(){return y(D(a,d.f,new q(function(){function c(d){var k=x(d);return k.h?new h(1,44,new q(function(){return y(D(a,k.f,new q(function(){return c(k.i)})))})):x(new h(1,93,b))}return c(d.i)})))})):J("[]",b)}
var Ab=new q(function(){return new aa(Ya,new l(function(a,c,b){a=x(c);return wb(a.f,a.i,a.G,a.d,a.l,b)},function(a){a=x(a);return wb(a.f,a.i,a.G,a.d,a.l,n)},function(a,c){return yb(xb,a,c)}),zb,function(a){a=x(a);return Za(x(x(a.f).f),Ya,a.i)})});function zb(a){return new h(0,Ab,a)}function Bb(a,c){return ha(new q(function(){return zb(new q(function(){return new ca(a)}))}))}var Cb=new q(function(){return I("Pattern match failure in do expression at src/Haste/Prim/Any.hs:272:5-9")});
function Db(a){return x(x(a).f)}function Eb(a,c){var b=Ua(Ma(0,a),c),d=x(b);if(d.h&&(b=x(d.i),b.h)){if(x(b.i).h)return 19<F?new r(function(){return Bb(Cb,c)}):(++F,Bb(Cb,c));d=y(fa(Db,Ta,d.f,c));b=y(fa(Db,Ta,b.f,c));return new h(0,d,b)}return 19<F?new r(function(){return Bb(Cb,c)}):(++F,Bb(Cb,c))}function Fb(a){a=y(C(a,la));return x(a)}var Ka=new q(function(){return Fb(function(a){return null})});
function Gb(a,c,b){if(7==x(a)){a=x(Ra)(c);var d=y(Eb(a,b)),e=c.deltaX,f=c.deltaY,k=c.deltaZ;return new q(function(){return new l(x(d),x(n),x(new l(e,f,k)))})}a=x(Ra)(c);var m=y(Eb(a,b));c=c.button;if(x(Ja(c)))return new q(function(){return new l(x(m),x(n),x(Qa))});var u=Pa(c,b);return new q(function(){return new l(x(m),x(new g(1,u)),x(Qa))})}function Hb(a,c,b){return Gb(a,x(c),b)}
function Ib(a){switch(x(a)){case 0:return"click";case 1:return"dblclick";case 2:return"mousedown";case 3:return"mouseup";case 4:return"mousemove";case 5:return"mouseover";case 6:return"mouseout";default:return"wheel"}}function Jb(a,c){return new g(1,a)}function Kb(a){return x(a)}var Lb=new h(0,function(a){return"()"},function(a){a=x(a);return 0==x("()"==a)?n:x(new g(1,0))});function Mb(a){return G(x(a))}var Nb=new h(0,Mb,function(a){return new g(1,new q(function(){return K(x(a))}))});
function Ob(a,c){return 19<F?new r(function(){return Bb(a,c)}):(++F,Bb(a,c))}function Pb(a,c,b){var d=y(C(a,b));return 19<F?new r(function(){return D(c,d,b)}):(++F,D(c,d,b))}function Qb(a,c){return a}function Rb(a,c,b){y(C(a,b));return 19<F?new r(function(){return C(c,b)}):(++F,C(c,b))}var Sb=new q(function(){return G(new h(1,38,n))}),Tb=new q(function(){return G(new h(1,61,n))});
function Ub(a,c){var b=x(c);return 0==b.h?n:new h(1,new q(function(){return y(C(a,b.f))}),new q(function(){return Ub(a,b.i)}))}function Vb(a){return x(x(a).f)}function Wb(a,c,b){b=na(Ub(function(b){var e=x(b);return na(new h(1,new q(function(){return y(D(Vb,a,e.f))}),new h(1,new q(function(){return y(D(Vb,c,e.i))}),n)),x(Tb))},b),x(Sb));return x(b)}
function Xb(a,c,b,d){var e=new XMLHttpRequest;e.open(a,c,!0);"POST"==a&&e.setRequestHeader("Content-type","application/x-www-form-urlencoded");e.onreadystatechange=function(){4==e.readyState&&d(200==e.status?e.responseText:null)};e.send(b)}var Yb=new q(function(){return G(new h(1,63,n))}),Zb=new q(function(){return G(n)});
function $b(a,c,b,d,e,f,k,m){function u(a){function u(a){function M(f){function p(b){var c=new q(function(){return x(x(d).i)});Xb(a,f,b,La(function(a,b){y(D(m,new q(function(){var b=x(a);return x(Ja(b))?n:y(C(c,new q(function(){return String(b)})))}),b));return Ka}));return 0}if(x(e)){var u=x(k);return u.h?p(Wb(c,b,u)):p(x(Zb))}return p(x(Zb))}if(x(e))return M(G(x(f)));if(x(k).h){var p=na(new h(1,H,new h(1,z,n)),x(Yb));return M(p)}return M(G(x(f)))}return x(e)?u("POST"):u("GET")}var z=new q(function(){return Wb(c,
b,k)}),H=new q(function(){return Mb(f)});return 19<F?new r(function(){return C(a,u)}):(++F,C(a,u))}function ac(a){return x(x(a).f)}function bc(a){return x(x(a).f)}var cc=new q(function(){return Fb(function(a){return{x:n}})});
function dc(a,c,b,d,e,f,k,m){function u(a){var b=new q(function(){return y(C(c,new q(function(){var b=La(function(b,c){y(D(x(a),b,c));return Ka});return function(a){a=x(va);var c=x(w);a.addEventListener(c,b,!1);return[b]}})))});return 19<F?new r(function(){return D(Q,b,z)}):(++F,D(Q,b,z))}function z(a){return 19<F?new r(function(){return C(H.G,new l(w,va,a))}):(++F,C(H.G,new l(w,va,a)))}var H=x(a),Q=H.f,va=new q(function(){return y(D(ac,d,f))}),w=new q(function(){return y(D(bc,e,k))}),M=new q(function(){var a=
new q(function(){return x(x(e).i)});return y(C(b,function(b){var d=new q(function(){return y(C(c,function(c){c=ja(x(cc),new g(1,b));return 19<F?new r(function(){return fa(a,k,b,c)}):(++F,fa(a,k,b,c))}))});return 19<F?new r(function(){return D(Q,d,m)}):(++F,D(Q,d,m))}))});return 19<F?new r(function(){return D(Q,M,u)}):(++F,D(Q,M,u))}var ec=new q(function(){return I("base")}),fc=new q(function(){return I("Control.Exception.Base")}),gc=new q(function(){return I("PatternMatchFail")});
function hc(a){return x(new aa(new N(18445595,3739165398,!0),new N(52003073,3246954884,!0),new ba(new N(18445595,3739165398,!0),new N(52003073,3246954884,!0),ec,fc,gc),n))}function ic(a,c){return Z(x(a).f,c)}var kc=new q(function(){return new aa(hc,new l(function(a,c,b){return Z(x(c).f,b)},function(a){return x(x(a).f)},function(a,c){return yb(ic,a,c)}),jc,function(a){a=x(a);return Za(x(x(a.f).f),hc,a.i)})});function jc(a){return new h(0,kc,a)}var lc=new q(function(){return I("Non-exhaustive patterns in")});
function mc(a){var c=jc;return ha(new q(function(){return y(C(c,a))}))}function nc(a,c){var b=x(c);if(b.h){var d=b.f;if(y(C(a,d))){var e=new q(function(){var c=nc(a,b.i);return new h(0,c.f,c.i)});return new h(0,new h(1,d,new q(function(){return x(x(e).f)})),new q(function(){return x(x(e).i)}))}return new h(0,n,b)}return new h(0,n,n)}function oc(a){return 124==x(a)?!1:!0}
function pc(a){function c(a,b){return Z(a,new q(function(){return J(": ",new q(function(){return Z(lc,new q(function(){return Z(b,new h(1,10,n))},1))}))},1))}var b=nc(oc,I(a));a=b.f;b=x(b.i);return b.h?124==x(b.f)?c(a,new h(1,32,b.i)):c(a,n):c(a,n)}function qc(a){return mc(new g(0,new q(function(){return pc(a)})))}var rc=new q(function(){return qc("ads_apply.hs:14:1-41|function onSubmitResultReturn")});function sc(a,c){return 0==x(a).h?x(rc):0}var tc=new q(function(){return alert});
function uc(a,c){return a[c].toString()}
var vc=new q(function(){return I("value")}),wc=new q(function(){return I("isJoined")}),xc=new q(function(){return I("captcha")}),yc=new q(function(){return I("ownerType")}),zc=new q(function(){return I("addPic")}),Ac=new q(function(){return I("(function(s){var reader=new FileReader();reader.readAsDataURL(document.getElementById(s).files[0]);return reader.result;})")}),Bc=new q(function(){return I("/api/advertisement/insertApplication")}),Cc=new q(function(){return I("Internal Error!")}),Dc=new q(function(){return I("\u9a8c\u8bc1\u7801\u9519\u8bef")}),
Ec=new q(function(){return qc("ads_apply.hs:(28,1)-(30,44)|function onCaptchaVerified")}),Fc=new q(function(){return I("adPic")}),Gc=new q(function(){return I("owner")}),Hc=new q(function(){return I("ownerContact")}),Ic=new q(function(){return I(" found!")});function Jc(a){return ia(J("No element with ID ",new q(function(){return Z(K(x(a)),Ic)})))}
function Kc(a,c){var b=x(a);if(b.h)if(b=x(b.f),b.h){var d=b.i;switch(x(b.f)){case 48:if(x(d).h)return x(Ec);x(tc)(G(x(Dc)));return 0;case 49:if(x(d).h)return x(Ec);var b=eval(G(x(Ac))),e=x(b)(G(x(zc))),b=x(Gc),d=G(b),f=document.getElementById(d),k=x(Ka);if(x(f===k))return Jc(d);var m=x(vc),u=uc(f,G(m)),z=function(a,b){var c=x(a);if(c.h){var d=x(c.f),e=G(d),f=document.getElementById(e);if(x(f===k))return Jc(e);var u=uc(f,G(m)),c=z(c.i,b);return new h(1,new h(0,d,new q(function(){return K(String(u))})),
c)}return n},d=function(a,b,c){a=x(a);var d=G(a),e=document.getElementById(d);if(x(e===k))return Jc(d);var f=uc(e,G(m));b=z(b,c);return new h(1,new h(0,a,new q(function(){return K(String(f))})),b)}(Hc,new h(1,yc,new h(1,wc,new h(1,xc,n))),c);y(v($b,[Kb,Nb,Nb,Nb,1,Bc,new h(1,new h(0,Fc,new q(function(){return K(String(e))})),new h(1,new h(0,b,new q(function(){return K(String(u))})),d)),sc,c]));return 0;default:return x(Ec)}}else return x(Ec);else return x(tc)(G(x(Cc))),0}
function Lc(a){var c=document.getElementById("btn_submit"),b=x(Ka);if(x(c===b))return Jc("btn_submit");y(v(dc,[new aa(Pb,Rb,Qb,Ob),Kb,Qb,new h(0,Kb,Jb),new h(0,Ib,Hb),c,0,function(a,c){var f=G(x(xc)),k=document.getElementById(f);if(x(k===b))return Jc(f);var m=uc(k,G(x(vc)));y(v($b,[Kb,Lb,Lb,Nb,0,new q(function(){return J("/api/captcha/verify?code=",new q(function(){return K(String(m))}))}),n,Kc,c]));return 0},a]));return 0}function Mc(a){return Lc(a)}window.onload=function(){y(v(Mc,[0]))};
